# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
enabled_platforms=fabric

# Version settings
minecraft_version=26.2
minecraft_version_range=>=26.2 <26.3

# Mapping settings
mapping_channel=official
mapping_version=26.2

# NeoForge
neoforge_version=21.1.219
neoforge_version_range=[21.1,)
neoforge_loader_version_range=[21.1,)

# Fabric
fabric_api_version=0.157.0+26.2
fabric_loader_version=0.19.3

## Mod Dependency properties

# Create (NeoForge)
create_neoforge_version = 6.0.10-280
flywheel_neoforge_version = 1.0.6
ponder_neoforge_version = 1.0.82
vanillin_neoforge_version = 1.0.0-beta-11
registrate_version = MC1.21-1.3.0+67

# Create (Fabric, not yet available on 1.21.)
#create_fabric_version = 0.5.1-d-build.1161+mc1.20.1

## Mod Properties

archives_base_name=DramaticDoors

mod_id=dramaticdoors
mod_name=Dramatic Doors
mod_version=1.20.1-3.3.3+26.2-workbench-canary6
mod_group_id=com.fizzware.dramaticdoors

mod_license=MIT
mod_authors=Fizzware, Kitteh6660
mod_description=Doors that are barely tall enough to fit your player ... ?\\n\\nDoors that suffocate you when you ride ol' Blackjack the horse through? Enderman discrimination? Seriously?\\n... PAH!!\\n\\nCan we not have intrigue?  Whatever happened to the tender grace and elegance of a nice tall door? Where is the drama?!?\\nHere. I have it. And now you can too.\\n\\nGone are the ways of the past - with the new Dramatic Doors mod!\\n\\nWith the modern era of innovations comes a new door type: the tall door and the short door. They come in every vanilla variety and support a myriad of mods on Fabric, Quilt, and NeoForge!
