plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.19'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

test {
    useJUnitPlatform()
    systemProperty 'projectRoot', projectDir.absolutePath
}

tasks.withType(AbstractArchiveTask).configureEach {
    includeEmptyDirs = false
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

java {
    withSourcesJar()
}
