package dev.resivore.blockfamilies.cnm.catalog;

import net.minecraft.resources.Identifier;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.BAR_CHAIN;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.BBB_DETAIL;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.BUILDING_ACCESSORY;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.DISPLAY_FIXTURE;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.FENCE_GATE;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.MASONRY_DETAIL;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.THREE_HIGH_DOOR;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.TRAPDOOR;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.TWO_HIGH_DOOR;
import static dev.resivore.blockfamilies.cnm.catalog.AuditedShapeFamily.Category.WINDOW;

/**
 * Literal registry identities approved by the 2026-08-26 CNM ShapeMap audit.
 *
 * <p>This catalog intentionally contains no registry-name parsing, suffix
 * matching, material inference, or optional-provider discovery. Updating a
 * provider version requires a new audit and a literal catalog change.</p>
 */
public final class AuditedShapeFamilies {
    public static final int EXPECTED_FAMILY_COUNT = 166;
    public static final int EXPECTED_UNIQUE_MEMBER_COUNT = 1_811;
    public static final int EXPECTED_LARGEST_FAMILY_SIZE = 38;

    private static final String KEY_NAMESPACE = "interchangeable_block_families";
    /*
     * These C7/C9 family shells are deliberately superseded, member-for-member,
     * by the complete C12 masonry families. Keeping both would give a provider
     * cell two ShapeMap owners.
     */
    private static final Set<String> C12_REHOMED_MASONRY_KEYS = Set.of(
            "cnm/window/andesite", "cnm/window/bricks", "cnm/window/dark_prismarine",
            "cnm/window/deepslate", "cnm/window/diorite", "cnm/window/granite",
            "cnm/window/polished_blackstone", "cnm/window/prismarine_bricks",
            "cnm/window/quartz_block", "cnm/window/red_sandstone", "cnm/window/sandstone",
            "cnm/window/stone",
            "cnm/bbb_detail/stone/stone", "cnm/bbb_detail/stone/blackstone",
            "cnm/bbb_detail/stone/deepslate", "cnm/bbb_detail/stone/nether_brick",
            "cnm/bbb_detail/stone/sandstone", "cnm/bbb_detail/stone/red_sandstone",
            "cnm/bbb_detail/stone/quartz",
            "cnm/building_accessory/stone", "cnm/building_accessory/polished_blackstone",
            "cnm/building_accessory/andesite", "cnm/building_accessory/diorite",
            "cnm/building_accessory/granite", "cnm/building_accessory/sandstone",
            "cnm/building_accessory/red_sandstone", "cnm/building_accessory/brick",
            "cnm/building_accessory/mossy_stone", "cnm/building_accessory/cobbled_deepslate",
            "cnm/building_accessory/deepslate", "cnm/building_accessory/mud_brick",
            "cnm/building_accessory/blackstone", "cnm/building_accessory/dark_prismarine");

    private static final List<AuditedShapeFamily> TWO_HIGH_DOORS = List.of(
            family("cnm/two_high_door/oak", TWO_HIGH_DOOR, minecraft("oak_door"),
                    mcwDoors("oak_bamboo_door"),
                    mcwDoors("oak_bark_glass_door"),
                    mcwDoors("oak_barn_door"),
                    mcwDoors("oak_barn_glass_door"),
                    mcwDoors("oak_beach_door"),
                    mcwDoors("oak_cottage_door"),
                    mcwDoors("oak_four_panel_door"),
                    mcwDoors("oak_glass_door"),
                    mcwDoors("oak_japanese_door"),
                    mcwDoors("oak_japanese2_door"),
                    mcwDoors("oak_modern_door"),
                    mcwDoors("oak_mystic_door"),
                    mcwDoors("oak_nether_door"),
                    mcwDoors("oak_paper_door"),
                    mcwDoors("oak_stable_door"),
                    mcwDoors("oak_stable_head_door"),
                    mcwDoors("oak_swamp_door"),
                    mcwDoors("oak_tropical_door"),
                    mcwDoors("oak_waffle_door"),
                    mcwDoors("oak_western_door"),
                    mcwDoors("oak_whispering_door")),
            family("cnm/two_high_door/spruce", TWO_HIGH_DOOR, minecraft("spruce_door"),
                    mcwDoors("spruce_bamboo_door"),
                    mcwDoors("spruce_bark_glass_door"),
                    mcwDoors("spruce_barn_door"),
                    mcwDoors("spruce_barn_glass_door"),
                    mcwDoors("spruce_beach_door"),
                    mcwDoors("spruce_classic_door"),
                    mcwDoors("spruce_four_panel_door"),
                    mcwDoors("spruce_glass_door"),
                    mcwDoors("spruce_japanese_door"),
                    mcwDoors("spruce_japanese2_door"),
                    mcwDoors("spruce_modern_door"),
                    mcwDoors("spruce_mystic_door"),
                    mcwDoors("spruce_nether_door"),
                    mcwDoors("spruce_paper_door"),
                    mcwDoors("spruce_stable_door"),
                    mcwDoors("spruce_stable_head_door"),
                    mcwDoors("spruce_swamp_door"),
                    mcwDoors("spruce_tropical_door"),
                    mcwDoors("spruce_waffle_door"),
                    mcwDoors("spruce_western_door"),
                    mcwDoors("spruce_whispering_door")),
            family("cnm/two_high_door/birch", TWO_HIGH_DOOR, minecraft("birch_door"),
                    mcwDoors("birch_bamboo_door"),
                    mcwDoors("birch_bark_glass_door"),
                    mcwDoors("birch_barn_door"),
                    mcwDoors("birch_barn_glass_door"),
                    mcwDoors("birch_beach_door"),
                    mcwDoors("birch_classic_door"),
                    mcwDoors("birch_cottage_door"),
                    mcwDoors("birch_four_panel_door"),
                    mcwDoors("birch_glass_door"),
                    mcwDoors("birch_japanese_door"),
                    mcwDoors("birch_japanese2_door"),
                    mcwDoors("birch_modern_door"),
                    mcwDoors("birch_mystic_door"),
                    mcwDoors("birch_nether_door"),
                    mcwDoors("birch_stable_door"),
                    mcwDoors("birch_stable_head_door"),
                    mcwDoors("birch_swamp_door"),
                    mcwDoors("birch_tropical_door"),
                    mcwDoors("birch_waffle_door"),
                    mcwDoors("birch_western_door"),
                    mcwDoors("birch_whispering_door")),
            family("cnm/two_high_door/jungle", TWO_HIGH_DOOR, minecraft("jungle_door"),
                    mcwDoors("jungle_bamboo_door"),
                    mcwDoors("jungle_bark_glass_door"),
                    mcwDoors("jungle_barn_door"),
                    mcwDoors("jungle_barn_glass_door"),
                    mcwDoors("jungle_classic_door"),
                    mcwDoors("jungle_cottage_door"),
                    mcwDoors("jungle_four_panel_door"),
                    mcwDoors("jungle_glass_door"),
                    mcwDoors("jungle_japanese_door"),
                    mcwDoors("jungle_japanese2_door"),
                    mcwDoors("jungle_modern_door"),
                    mcwDoors("jungle_mystic_door"),
                    mcwDoors("jungle_nether_door"),
                    mcwDoors("jungle_paper_door"),
                    mcwDoors("jungle_stable_door"),
                    mcwDoors("jungle_stable_head_door"),
                    mcwDoors("jungle_swamp_door"),
                    mcwDoors("jungle_tropical_door"),
                    mcwDoors("jungle_waffle_door"),
                    mcwDoors("jungle_western_door"),
                    mcwDoors("jungle_whispering_door")),
            family("cnm/two_high_door/acacia", TWO_HIGH_DOOR, minecraft("acacia_door"),
                    mcwDoors("acacia_bamboo_door"),
                    mcwDoors("acacia_bark_glass_door"),
                    mcwDoors("acacia_barn_door"),
                    mcwDoors("acacia_barn_glass_door"),
                    mcwDoors("acacia_beach_door"),
                    mcwDoors("acacia_classic_door"),
                    mcwDoors("acacia_cottage_door"),
                    mcwDoors("acacia_four_panel_door"),
                    mcwDoors("acacia_glass_door"),
                    mcwDoors("acacia_japanese_door"),
                    mcwDoors("acacia_japanese2_door"),
                    mcwDoors("acacia_modern_door"),
                    mcwDoors("acacia_mystic_door"),
                    mcwDoors("acacia_nether_door"),
                    mcwDoors("acacia_paper_door"),
                    mcwDoors("acacia_stable_door"),
                    mcwDoors("acacia_stable_head_door"),
                    mcwDoors("acacia_swamp_door"),
                    mcwDoors("acacia_waffle_door"),
                    mcwDoors("acacia_western_door"),
                    mcwDoors("acacia_whispering_door")),
            family("cnm/two_high_door/dark_oak", TWO_HIGH_DOOR, minecraft("dark_oak_door"),
                    mcwDoors("dark_oak_bamboo_door"),
                    mcwDoors("dark_oak_bark_glass_door"),
                    mcwDoors("dark_oak_barn_door"),
                    mcwDoors("dark_oak_barn_glass_door"),
                    mcwDoors("dark_oak_beach_door"),
                    mcwDoors("dark_oak_classic_door"),
                    mcwDoors("dark_oak_cottage_door"),
                    mcwDoors("dark_oak_glass_door"),
                    mcwDoors("dark_oak_japanese_door"),
                    mcwDoors("dark_oak_japanese2_door"),
                    mcwDoors("dark_oak_modern_door"),
                    mcwDoors("dark_oak_mystic_door"),
                    mcwDoors("dark_oak_nether_door"),
                    mcwDoors("dark_oak_paper_door"),
                    mcwDoors("dark_oak_stable_door"),
                    mcwDoors("dark_oak_stable_head_door"),
                    mcwDoors("dark_oak_swamp_door"),
                    mcwDoors("dark_oak_tropical_door"),
                    mcwDoors("dark_oak_waffle_door"),
                    mcwDoors("dark_oak_western_door"),
                    mcwDoors("dark_oak_whispering_door")),
            family("cnm/two_high_door/mangrove", TWO_HIGH_DOOR, minecraft("mangrove_door"),
                    mcwDoors("mangrove_bamboo_door"),
                    mcwDoors("mangrove_bark_glass_door"),
                    mcwDoors("mangrove_barn_door"),
                    mcwDoors("mangrove_barn_glass_door"),
                    mcwDoors("mangrove_beach_door"),
                    mcwDoors("mangrove_classic_door"),
                    mcwDoors("mangrove_cottage_door"),
                    mcwDoors("mangrove_four_panel_door"),
                    mcwDoors("mangrove_glass_door"),
                    mcwDoors("mangrove_japanese_door"),
                    mcwDoors("mangrove_japanese2_door"),
                    mcwDoors("mangrove_modern_door"),
                    mcwDoors("mangrove_mystic_door"),
                    mcwDoors("mangrove_nether_door"),
                    mcwDoors("mangrove_paper_door"),
                    mcwDoors("mangrove_stable_door"),
                    mcwDoors("mangrove_stable_head_door"),
                    mcwDoors("mangrove_tropical_door"),
                    mcwDoors("mangrove_waffle_door"),
                    mcwDoors("mangrove_western_door"),
                    mcwDoors("mangrove_whispering_door")),
            family("cnm/two_high_door/cherry", TWO_HIGH_DOOR, minecraft("cherry_door"),
                    mcwDoors("cherry_bamboo_door"),
                    mcwDoors("cherry_bark_glass_door"),
                    mcwDoors("cherry_barn_door"),
                    mcwDoors("cherry_barn_glass_door"),
                    mcwDoors("cherry_beach_door"),
                    mcwDoors("cherry_classic_door"),
                    mcwDoors("cherry_cottage_door"),
                    mcwDoors("cherry_four_panel_door"),
                    mcwDoors("cherry_glass_door"),
                    mcwDoors("cherry_japanese_door"),
                    mcwDoors("cherry_japanese2_door"),
                    mcwDoors("cherry_modern_door"),
                    mcwDoors("cherry_mystic_door"),
                    mcwDoors("cherry_nether_door"),
                    mcwDoors("cherry_paper_door"),
                    mcwDoors("cherry_stable_door"),
                    mcwDoors("cherry_stable_head_door"),
                    mcwDoors("cherry_swamp_door"),
                    mcwDoors("cherry_tropical_door"),
                    mcwDoors("cherry_western_door"),
                    mcwDoors("cherry_whispering_door")),
            family("cnm/two_high_door/pale_oak", TWO_HIGH_DOOR, minecraft("pale_oak_door"),
                    mcwDoors("pale_oak_bamboo_door"),
                    mcwDoors("pale_oak_bark_glass_door"),
                    mcwDoors("pale_oak_barn_door"),
                    mcwDoors("pale_oak_barn_glass_door"),
                    mcwDoors("pale_oak_beach_door"),
                    mcwDoors("pale_oak_classic_door"),
                    mcwDoors("pale_oak_cottage_door"),
                    mcwDoors("pale_oak_four_panel_door"),
                    mcwDoors("pale_oak_glass_door"),
                    mcwDoors("pale_oak_japanese_door"),
                    mcwDoors("pale_oak_japanese2_door"),
                    mcwDoors("pale_oak_modern_door"),
                    mcwDoors("pale_oak_mystic_door"),
                    mcwDoors("pale_oak_nether_door"),
                    mcwDoors("pale_oak_paper_door"),
                    mcwDoors("pale_oak_stable_door"),
                    mcwDoors("pale_oak_stable_head_door"),
                    mcwDoors("pale_oak_swamp_door"),
                    mcwDoors("pale_oak_tropical_door"),
                    mcwDoors("pale_oak_waffle_door"),
                    mcwDoors("pale_oak_western_door")),
            family("cnm/two_high_door/bamboo", TWO_HIGH_DOOR, minecraft("bamboo_door"),
                    mcwDoors("bamboo_bark_glass_door"),
                    mcwDoors("bamboo_barn_door"),
                    mcwDoors("bamboo_barn_glass_door"),
                    mcwDoors("bamboo_beach_door"),
                    mcwDoors("bamboo_classic_door"),
                    mcwDoors("bamboo_cottage_door"),
                    mcwDoors("bamboo_four_panel_door"),
                    mcwDoors("bamboo_glass_door"),
                    mcwDoors("bamboo_japanese_door"),
                    mcwDoors("bamboo_japanese2_door"),
                    mcwDoors("bamboo_modern_door"),
                    mcwDoors("bamboo_mystic_door"),
                    mcwDoors("bamboo_nether_door"),
                    mcwDoors("bamboo_paper_door"),
                    mcwDoors("bamboo_stable_door"),
                    mcwDoors("bamboo_stable_head_door"),
                    mcwDoors("bamboo_swamp_door"),
                    mcwDoors("bamboo_tropical_door"),
                    mcwDoors("bamboo_waffle_door"),
                    mcwDoors("bamboo_western_door"),
                    mcwDoors("bamboo_whispering_door")),
            family("cnm/two_high_door/crimson", TWO_HIGH_DOOR, minecraft("crimson_door"),
                    mcwDoors("crimson_bamboo_door"),
                    mcwDoors("crimson_barn_door"),
                    mcwDoors("crimson_barn_glass_door"),
                    mcwDoors("crimson_beach_door"),
                    mcwDoors("crimson_classic_door"),
                    mcwDoors("crimson_cottage_door"),
                    mcwDoors("crimson_four_panel_door"),
                    mcwDoors("crimson_glass_door"),
                    mcwDoors("crimson_japanese_door"),
                    mcwDoors("crimson_japanese2_door"),
                    mcwDoors("crimson_modern_door"),
                    mcwDoors("crimson_mystic_door"),
                    mcwDoors("crimson_paper_door"),
                    mcwDoors("crimson_stable_door"),
                    mcwDoors("crimson_stable_head_door"),
                    mcwDoors("crimson_stem_glass_door"),
                    mcwDoors("crimson_swamp_door"),
                    mcwDoors("crimson_tropical_door"),
                    mcwDoors("crimson_waffle_door"),
                    mcwDoors("crimson_western_door"),
                    mcwDoors("crimson_whispering_door")),
            family("cnm/two_high_door/warped", TWO_HIGH_DOOR, minecraft("warped_door"),
                    mcwDoors("warped_bamboo_door"),
                    mcwDoors("warped_barn_door"),
                    mcwDoors("warped_barn_glass_door"),
                    mcwDoors("warped_beach_door"),
                    mcwDoors("warped_classic_door"),
                    mcwDoors("warped_cottage_door"),
                    mcwDoors("warped_four_panel_door"),
                    mcwDoors("warped_glass_door"),
                    mcwDoors("warped_japanese_door"),
                    mcwDoors("warped_japanese2_door"),
                    mcwDoors("warped_modern_door"),
                    mcwDoors("warped_nether_door"),
                    mcwDoors("warped_paper_door"),
                    mcwDoors("warped_stable_door"),
                    mcwDoors("warped_stable_head_door"),
                    mcwDoors("warped_stem_glass_door"),
                    mcwDoors("warped_swamp_door"),
                    mcwDoors("warped_tropical_door"),
                    mcwDoors("warped_waffle_door"),
                    mcwDoors("warped_western_door"),
                    mcwDoors("warped_whispering_door")),
            family("cnm/two_high_door/iron", TWO_HIGH_DOOR, minecraft("iron_door"),
                    mcwDoors("jail_door"),
                    mcwDoors("metal_door"),
                    mcwDoors("metal_hospital_door"),
                    mcwDoors("metal_reinforced_door"),
                    mcwDoors("metal_warning_door"),
                    mcwDoors("metal_windowed_door"),
                    mcwDoors("sliding_glass_door"),
                    mcwDoors("store_door"))
    );

    private static final List<AuditedShapeFamily> THREE_HIGH_DOORS = List.of(
            family("cnm/three_high_door/oak", THREE_HIGH_DOOR, dramaticDoors("tall_oak_door"),
                    dramaticDoors("tall_macaw_oak_bamboo_door"),
                    dramaticDoors("tall_macaw_oak_bark_glass_door"),
                    dramaticDoors("tall_macaw_oak_barn_door"),
                    dramaticDoors("tall_macaw_oak_barn_glass_door"),
                    dramaticDoors("tall_macaw_oak_beach_door"),
                    dramaticDoors("tall_macaw_oak_cottage_door"),
                    dramaticDoors("tall_macaw_oak_four_panel_door"),
                    dramaticDoors("tall_macaw_oak_glass_door"),
                    dramaticDoors("tall_macaw_oak_japanese_door"),
                    dramaticDoors("tall_macaw_oak_japanese2_door"),
                    dramaticDoors("tall_macaw_oak_modern_door"),
                    dramaticDoors("tall_macaw_oak_mystic_door"),
                    dramaticDoors("tall_macaw_oak_nether_door"),
                    dramaticDoors("tall_macaw_oak_paper_door"),
                    dramaticDoors("tall_macaw_oak_stable_door"),
                    dramaticDoors("tall_macaw_oak_stable_head_door"),
                    dramaticDoors("tall_macaw_oak_swamp_door"),
                    dramaticDoors("tall_macaw_oak_tropical_door"),
                    dramaticDoors("tall_macaw_oak_waffle_door")),
            family("cnm/three_high_door/spruce", THREE_HIGH_DOOR, dramaticDoors("tall_spruce_door"),
                    dramaticDoors("tall_macaw_spruce_bamboo_door"),
                    dramaticDoors("tall_macaw_spruce_bark_glass_door"),
                    dramaticDoors("tall_macaw_spruce_barn_door"),
                    dramaticDoors("tall_macaw_spruce_barn_glass_door"),
                    dramaticDoors("tall_macaw_spruce_beach_door"),
                    dramaticDoors("tall_macaw_spruce_classic_door"),
                    dramaticDoors("tall_macaw_spruce_four_panel_door"),
                    dramaticDoors("tall_macaw_spruce_glass_door"),
                    dramaticDoors("tall_macaw_spruce_japanese_door"),
                    dramaticDoors("tall_macaw_spruce_japanese2_door"),
                    dramaticDoors("tall_macaw_spruce_modern_door"),
                    dramaticDoors("tall_macaw_spruce_mystic_door"),
                    dramaticDoors("tall_macaw_spruce_nether_door"),
                    dramaticDoors("tall_macaw_spruce_paper_door"),
                    dramaticDoors("tall_macaw_spruce_stable_door"),
                    dramaticDoors("tall_macaw_spruce_stable_head_door"),
                    dramaticDoors("tall_macaw_spruce_swamp_door"),
                    dramaticDoors("tall_macaw_spruce_tropical_door"),
                    dramaticDoors("tall_macaw_spruce_waffle_door")),
            family("cnm/three_high_door/birch", THREE_HIGH_DOOR, dramaticDoors("tall_birch_door"),
                    dramaticDoors("tall_macaw_birch_bamboo_door"),
                    dramaticDoors("tall_macaw_birch_bark_glass_door"),
                    dramaticDoors("tall_macaw_birch_barn_door"),
                    dramaticDoors("tall_macaw_birch_barn_glass_door"),
                    dramaticDoors("tall_macaw_birch_beach_door"),
                    dramaticDoors("tall_macaw_birch_classic_door"),
                    dramaticDoors("tall_macaw_birch_cottage_door"),
                    dramaticDoors("tall_macaw_birch_four_panel_door"),
                    dramaticDoors("tall_macaw_birch_glass_door"),
                    dramaticDoors("tall_macaw_birch_japanese_door"),
                    dramaticDoors("tall_macaw_birch_japanese2_door"),
                    dramaticDoors("tall_macaw_birch_modern_door"),
                    dramaticDoors("tall_macaw_birch_mystic_door"),
                    dramaticDoors("tall_macaw_birch_nether_door"),
                    dramaticDoors("tall_macaw_birch_stable_door"),
                    dramaticDoors("tall_macaw_birch_stable_head_door"),
                    dramaticDoors("tall_macaw_birch_swamp_door"),
                    dramaticDoors("tall_macaw_birch_tropical_door"),
                    dramaticDoors("tall_macaw_birch_waffle_door")),
            family("cnm/three_high_door/jungle", THREE_HIGH_DOOR, dramaticDoors("tall_jungle_door"),
                    dramaticDoors("tall_macaw_jungle_bamboo_door"),
                    dramaticDoors("tall_macaw_jungle_bark_glass_door"),
                    dramaticDoors("tall_macaw_jungle_barn_door"),
                    dramaticDoors("tall_macaw_jungle_barn_glass_door"),
                    dramaticDoors("tall_macaw_jungle_classic_door"),
                    dramaticDoors("tall_macaw_jungle_cottage_door"),
                    dramaticDoors("tall_macaw_jungle_four_panel_door"),
                    dramaticDoors("tall_macaw_jungle_glass_door"),
                    dramaticDoors("tall_macaw_jungle_japanese_door"),
                    dramaticDoors("tall_macaw_jungle_japanese2_door"),
                    dramaticDoors("tall_macaw_jungle_modern_door"),
                    dramaticDoors("tall_macaw_jungle_mystic_door"),
                    dramaticDoors("tall_macaw_jungle_nether_door"),
                    dramaticDoors("tall_macaw_jungle_paper_door"),
                    dramaticDoors("tall_macaw_jungle_stable_door"),
                    dramaticDoors("tall_macaw_jungle_stable_head_door"),
                    dramaticDoors("tall_macaw_jungle_swamp_door"),
                    dramaticDoors("tall_macaw_jungle_tropical_door"),
                    dramaticDoors("tall_macaw_jungle_waffle_door")),
            family("cnm/three_high_door/acacia", THREE_HIGH_DOOR, dramaticDoors("tall_acacia_door"),
                    dramaticDoors("tall_macaw_acacia_bamboo_door"),
                    dramaticDoors("tall_macaw_acacia_bark_glass_door"),
                    dramaticDoors("tall_macaw_acacia_barn_door"),
                    dramaticDoors("tall_macaw_acacia_barn_glass_door"),
                    dramaticDoors("tall_macaw_acacia_beach_door"),
                    dramaticDoors("tall_macaw_acacia_classic_door"),
                    dramaticDoors("tall_macaw_acacia_cottage_door"),
                    dramaticDoors("tall_macaw_acacia_four_panel_door"),
                    dramaticDoors("tall_macaw_acacia_glass_door"),
                    dramaticDoors("tall_macaw_acacia_japanese_door"),
                    dramaticDoors("tall_macaw_acacia_japanese2_door"),
                    dramaticDoors("tall_macaw_acacia_modern_door"),
                    dramaticDoors("tall_macaw_acacia_mystic_door"),
                    dramaticDoors("tall_macaw_acacia_nether_door"),
                    dramaticDoors("tall_macaw_acacia_paper_door"),
                    dramaticDoors("tall_macaw_acacia_stable_door"),
                    dramaticDoors("tall_macaw_acacia_stable_head_door"),
                    dramaticDoors("tall_macaw_acacia_swamp_door"),
                    dramaticDoors("tall_macaw_acacia_waffle_door")),
            family("cnm/three_high_door/dark_oak", THREE_HIGH_DOOR, dramaticDoors("tall_dark_oak_door"),
                    dramaticDoors("tall_macaw_dark_oak_bamboo_door"),
                    dramaticDoors("tall_macaw_dark_oak_bark_glass_door"),
                    dramaticDoors("tall_macaw_dark_oak_barn_door"),
                    dramaticDoors("tall_macaw_dark_oak_barn_glass_door"),
                    dramaticDoors("tall_macaw_dark_oak_beach_door"),
                    dramaticDoors("tall_macaw_dark_oak_classic_door"),
                    dramaticDoors("tall_macaw_dark_oak_cottage_door"),
                    dramaticDoors("tall_macaw_dark_oak_glass_door"),
                    dramaticDoors("tall_macaw_dark_oak_japanese_door"),
                    dramaticDoors("tall_macaw_dark_oak_japanese2_door"),
                    dramaticDoors("tall_macaw_dark_oak_modern_door"),
                    dramaticDoors("tall_macaw_dark_oak_mystic_door"),
                    dramaticDoors("tall_macaw_dark_oak_nether_door"),
                    dramaticDoors("tall_macaw_dark_oak_paper_door"),
                    dramaticDoors("tall_macaw_dark_oak_stable_door"),
                    dramaticDoors("tall_macaw_dark_oak_stable_head_door"),
                    dramaticDoors("tall_macaw_dark_oak_swamp_door"),
                    dramaticDoors("tall_macaw_dark_oak_tropical_door"),
                    dramaticDoors("tall_macaw_dark_oak_waffle_door")),
            family("cnm/three_high_door/mangrove", THREE_HIGH_DOOR, dramaticDoors("tall_mangrove_door"),
                    dramaticDoors("tall_macaw_mangrove_bamboo_door"),
                    dramaticDoors("tall_macaw_mangrove_bark_glass_door"),
                    dramaticDoors("tall_macaw_mangrove_barn_door"),
                    dramaticDoors("tall_macaw_mangrove_barn_glass_door"),
                    dramaticDoors("tall_macaw_mangrove_beach_door"),
                    dramaticDoors("tall_macaw_mangrove_classic_door"),
                    dramaticDoors("tall_macaw_mangrove_cottage_door"),
                    dramaticDoors("tall_macaw_mangrove_four_panel_door"),
                    dramaticDoors("tall_macaw_mangrove_glass_door"),
                    dramaticDoors("tall_macaw_mangrove_japanese_door"),
                    dramaticDoors("tall_macaw_mangrove_japanese2_door"),
                    dramaticDoors("tall_macaw_mangrove_modern_door"),
                    dramaticDoors("tall_macaw_mangrove_mystic_door"),
                    dramaticDoors("tall_macaw_mangrove_nether_door"),
                    dramaticDoors("tall_macaw_mangrove_paper_door"),
                    dramaticDoors("tall_macaw_mangrove_stable_door"),
                    dramaticDoors("tall_macaw_mangrove_stable_head_door"),
                    dramaticDoors("tall_macaw_mangrove_tropical_door"),
                    dramaticDoors("tall_macaw_mangrove_waffle_door")),
            family("cnm/three_high_door/cherry", THREE_HIGH_DOOR, dramaticDoors("tall_cherry_door"),
                    dramaticDoors("tall_macaw_cherry_bamboo_door"),
                    dramaticDoors("tall_macaw_cherry_bark_glass_door"),
                    dramaticDoors("tall_macaw_cherry_barn_door"),
                    dramaticDoors("tall_macaw_cherry_barn_glass_door"),
                    dramaticDoors("tall_macaw_cherry_beach_door"),
                    dramaticDoors("tall_macaw_cherry_classic_door"),
                    dramaticDoors("tall_macaw_cherry_cottage_door"),
                    dramaticDoors("tall_macaw_cherry_four_panel_door"),
                    dramaticDoors("tall_macaw_cherry_glass_door"),
                    dramaticDoors("tall_macaw_cherry_japanese_door"),
                    dramaticDoors("tall_macaw_cherry_japanese2_door"),
                    dramaticDoors("tall_macaw_cherry_modern_door"),
                    dramaticDoors("tall_macaw_cherry_mystic_door"),
                    dramaticDoors("tall_macaw_cherry_nether_door"),
                    dramaticDoors("tall_macaw_cherry_paper_door"),
                    dramaticDoors("tall_macaw_cherry_stable_door"),
                    dramaticDoors("tall_macaw_cherry_stable_head_door"),
                    dramaticDoors("tall_macaw_cherry_swamp_door"),
                    dramaticDoors("tall_macaw_cherry_tropical_door")),
            family("cnm/three_high_door/bamboo", THREE_HIGH_DOOR, dramaticDoors("tall_bamboo_door"),
                    dramaticDoors("tall_macaw_bamboo_bark_glass_door"),
                    dramaticDoors("tall_macaw_bamboo_barn_door"),
                    dramaticDoors("tall_macaw_bamboo_barn_glass_door"),
                    dramaticDoors("tall_macaw_bamboo_beach_door"),
                    dramaticDoors("tall_macaw_bamboo_classic_door"),
                    dramaticDoors("tall_macaw_bamboo_cottage_door"),
                    dramaticDoors("tall_macaw_bamboo_four_panel_door"),
                    dramaticDoors("tall_macaw_bamboo_glass_door"),
                    dramaticDoors("tall_macaw_bamboo_japanese_door"),
                    dramaticDoors("tall_macaw_bamboo_japanese2_door"),
                    dramaticDoors("tall_macaw_bamboo_modern_door"),
                    dramaticDoors("tall_macaw_bamboo_mystic_door"),
                    dramaticDoors("tall_macaw_bamboo_nether_door"),
                    dramaticDoors("tall_macaw_bamboo_paper_door"),
                    dramaticDoors("tall_macaw_bamboo_stable_door"),
                    dramaticDoors("tall_macaw_bamboo_stable_head_door"),
                    dramaticDoors("tall_macaw_bamboo_swamp_door"),
                    dramaticDoors("tall_macaw_bamboo_tropical_door"),
                    dramaticDoors("tall_macaw_bamboo_waffle_door")),
            family("cnm/three_high_door/crimson", THREE_HIGH_DOOR, dramaticDoors("tall_crimson_door"),
                    dramaticDoors("tall_macaw_crimson_bamboo_door"),
                    dramaticDoors("tall_macaw_crimson_barn_door"),
                    dramaticDoors("tall_macaw_crimson_barn_glass_door"),
                    dramaticDoors("tall_macaw_crimson_beach_door"),
                    dramaticDoors("tall_macaw_crimson_classic_door"),
                    dramaticDoors("tall_macaw_crimson_cottage_door"),
                    dramaticDoors("tall_macaw_crimson_four_panel_door"),
                    dramaticDoors("tall_macaw_crimson_glass_door"),
                    dramaticDoors("tall_macaw_crimson_japanese_door"),
                    dramaticDoors("tall_macaw_crimson_japanese2_door"),
                    dramaticDoors("tall_macaw_crimson_modern_door"),
                    dramaticDoors("tall_macaw_crimson_mystic_door"),
                    dramaticDoors("tall_macaw_crimson_paper_door"),
                    dramaticDoors("tall_macaw_crimson_stable_door"),
                    dramaticDoors("tall_macaw_crimson_stable_head_door"),
                    dramaticDoors("tall_macaw_crimson_stem_glass_door"),
                    dramaticDoors("tall_macaw_crimson_swamp_door"),
                    dramaticDoors("tall_macaw_crimson_tropical_door"),
                    dramaticDoors("tall_macaw_crimson_waffle_door")),
            family("cnm/three_high_door/warped", THREE_HIGH_DOOR, dramaticDoors("tall_warped_door"),
                    dramaticDoors("tall_macaw_warped_bamboo_door"),
                    dramaticDoors("tall_macaw_warped_barn_door"),
                    dramaticDoors("tall_macaw_warped_barn_glass_door"),
                    dramaticDoors("tall_macaw_warped_beach_door"),
                    dramaticDoors("tall_macaw_warped_classic_door"),
                    dramaticDoors("tall_macaw_warped_cottage_door"),
                    dramaticDoors("tall_macaw_warped_four_panel_door"),
                    dramaticDoors("tall_macaw_warped_glass_door"),
                    dramaticDoors("tall_macaw_warped_japanese_door"),
                    dramaticDoors("tall_macaw_warped_japanese2_door"),
                    dramaticDoors("tall_macaw_warped_modern_door"),
                    dramaticDoors("tall_macaw_warped_nether_door"),
                    dramaticDoors("tall_macaw_warped_paper_door"),
                    dramaticDoors("tall_macaw_warped_stable_door"),
                    dramaticDoors("tall_macaw_warped_stable_head_door"),
                    dramaticDoors("tall_macaw_warped_stem_glass_door"),
                    dramaticDoors("tall_macaw_warped_swamp_door"),
                    dramaticDoors("tall_macaw_warped_tropical_door"),
                    dramaticDoors("tall_macaw_warped_waffle_door")),
            family("cnm/three_high_door/iron", THREE_HIGH_DOOR, dramaticDoors("tall_iron_door"),
                    dramaticDoors("tall_macaw_store_door"),
                    dramaticDoors("tall_macaw_sliding_glass_door"),
                    dramaticDoors("tall_macaw_jail_door"),
                    dramaticDoors("tall_macaw_metal_door"),
                    dramaticDoors("tall_macaw_metal_hospital_door"),
                    dramaticDoors("tall_macaw_metal_reinforced_door"),
                    dramaticDoors("tall_macaw_metal_warning_door"),
                    dramaticDoors("tall_macaw_metal_windowed_door"))
    );

    private static final List<AuditedShapeFamily> TRAPDOORS = List.of(
            family("cnm/trapdoor/oak", TRAPDOOR, minecraft("oak_trapdoor"),
                    mcwTrapdoors("oak_bamboo_trapdoor"),
                    mcwTrapdoors("oak_bark_trapdoor"),
                    mcwTrapdoors("oak_barn_trapdoor"),
                    mcwTrapdoors("oak_barred_trapdoor"),
                    mcwTrapdoors("oak_barrel_trapdoor"),
                    mcwTrapdoors("oak_beach_trapdoor"),
                    mcwTrapdoors("oak_blossom_trapdoor"),
                    mcwTrapdoors("oak_cottage_trapdoor"),
                    mcwTrapdoors("oak_four_panel_trapdoor"),
                    mcwTrapdoors("oak_glass_trapdoor"),
                    mcwTrapdoors("oak_mystic_trapdoor"),
                    mcwTrapdoors("oak_paper_trapdoor"),
                    mcwTrapdoors("oak_ranch_trapdoor"),
                    mcwTrapdoors("oak_swamp_trapdoor"),
                    mcwTrapdoors("oak_tropical_trapdoor"),
                    mcwTrapdoors("oak_whispering_trapdoor"),
                    mcwWindows("oak_shutter"),
                    mcwWindows("oak_louvered_shutter")),
            family("cnm/trapdoor/spruce", TRAPDOOR, minecraft("spruce_trapdoor"),
                    mcwTrapdoors("spruce_bamboo_trapdoor"),
                    mcwTrapdoors("spruce_bark_trapdoor"),
                    mcwTrapdoors("spruce_barn_trapdoor"),
                    mcwTrapdoors("spruce_barred_trapdoor"),
                    mcwTrapdoors("spruce_barrel_trapdoor"),
                    mcwTrapdoors("spruce_beach_trapdoor"),
                    mcwTrapdoors("spruce_blossom_trapdoor"),
                    mcwTrapdoors("spruce_classic_trapdoor"),
                    mcwTrapdoors("spruce_four_panel_trapdoor"),
                    mcwTrapdoors("spruce_glass_trapdoor"),
                    mcwTrapdoors("spruce_mystic_trapdoor"),
                    mcwTrapdoors("spruce_paper_trapdoor"),
                    mcwTrapdoors("spruce_ranch_trapdoor"),
                    mcwTrapdoors("spruce_swamp_trapdoor"),
                    mcwTrapdoors("spruce_tropical_trapdoor"),
                    mcwTrapdoors("spruce_whispering_trapdoor"),
                    mcwWindows("spruce_shutter"),
                    mcwWindows("spruce_louvered_shutter")),
            family("cnm/trapdoor/birch", TRAPDOOR, minecraft("birch_trapdoor"),
                    mcwTrapdoors("birch_bamboo_trapdoor"),
                    mcwTrapdoors("birch_bark_trapdoor"),
                    mcwTrapdoors("birch_barn_trapdoor"),
                    mcwTrapdoors("birch_barred_trapdoor"),
                    mcwTrapdoors("birch_barrel_trapdoor"),
                    mcwTrapdoors("birch_beach_trapdoor"),
                    mcwTrapdoors("birch_blossom_trapdoor"),
                    mcwTrapdoors("birch_classic_trapdoor"),
                    mcwTrapdoors("birch_cottage_trapdoor"),
                    mcwTrapdoors("birch_four_panel_trapdoor"),
                    mcwTrapdoors("birch_glass_trapdoor"),
                    mcwTrapdoors("birch_mystic_trapdoor"),
                    mcwTrapdoors("birch_ranch_trapdoor"),
                    mcwTrapdoors("birch_swamp_trapdoor"),
                    mcwTrapdoors("birch_tropical_trapdoor"),
                    mcwTrapdoors("birch_whispering_trapdoor"),
                    mcwWindows("birch_shutter"),
                    mcwWindows("birch_louvered_shutter")),
            family("cnm/trapdoor/jungle", TRAPDOOR, minecraft("jungle_trapdoor"),
                    mcwTrapdoors("jungle_bamboo_trapdoor"),
                    mcwTrapdoors("jungle_bark_trapdoor"),
                    mcwTrapdoors("jungle_barn_trapdoor"),
                    mcwTrapdoors("jungle_barred_trapdoor"),
                    mcwTrapdoors("jungle_barrel_trapdoor"),
                    mcwTrapdoors("jungle_blossom_trapdoor"),
                    mcwTrapdoors("jungle_classic_trapdoor"),
                    mcwTrapdoors("jungle_cottage_trapdoor"),
                    mcwTrapdoors("jungle_four_panel_trapdoor"),
                    mcwTrapdoors("jungle_glass_trapdoor"),
                    mcwTrapdoors("jungle_mystic_trapdoor"),
                    mcwTrapdoors("jungle_paper_trapdoor"),
                    mcwTrapdoors("jungle_ranch_trapdoor"),
                    mcwTrapdoors("jungle_swamp_trapdoor"),
                    mcwTrapdoors("jungle_tropical_trapdoor"),
                    mcwTrapdoors("jungle_whispering_trapdoor"),
                    mcwWindows("jungle_shutter"),
                    mcwWindows("jungle_louvered_shutter")),
            family("cnm/trapdoor/acacia", TRAPDOOR, minecraft("acacia_trapdoor"),
                    mcwTrapdoors("acacia_bamboo_trapdoor"),
                    mcwTrapdoors("acacia_bark_trapdoor"),
                    mcwTrapdoors("acacia_barn_trapdoor"),
                    mcwTrapdoors("acacia_barred_trapdoor"),
                    mcwTrapdoors("acacia_barrel_trapdoor"),
                    mcwTrapdoors("acacia_beach_trapdoor"),
                    mcwTrapdoors("acacia_blossom_trapdoor"),
                    mcwTrapdoors("acacia_classic_trapdoor"),
                    mcwTrapdoors("acacia_cottage_trapdoor"),
                    mcwTrapdoors("acacia_four_panel_trapdoor"),
                    mcwTrapdoors("acacia_glass_trapdoor"),
                    mcwTrapdoors("acacia_mystic_trapdoor"),
                    mcwTrapdoors("acacia_paper_trapdoor"),
                    mcwTrapdoors("acacia_ranch_trapdoor"),
                    mcwTrapdoors("acacia_swamp_trapdoor"),
                    mcwTrapdoors("acacia_whispering_trapdoor"),
                    mcwWindows("acacia_shutter"),
                    mcwWindows("acacia_louvered_shutter")),
            family("cnm/trapdoor/dark_oak", TRAPDOOR, minecraft("dark_oak_trapdoor"),
                    mcwTrapdoors("dark_oak_bamboo_trapdoor"),
                    mcwTrapdoors("dark_oak_bark_trapdoor"),
                    mcwTrapdoors("dark_oak_barn_trapdoor"),
                    mcwTrapdoors("dark_oak_barred_trapdoor"),
                    mcwTrapdoors("dark_oak_barrel_trapdoor"),
                    mcwTrapdoors("dark_oak_beach_trapdoor"),
                    mcwTrapdoors("dark_oak_blossom_trapdoor"),
                    mcwTrapdoors("dark_oak_classic_trapdoor"),
                    mcwTrapdoors("dark_oak_cottage_trapdoor"),
                    mcwTrapdoors("dark_oak_glass_trapdoor"),
                    mcwTrapdoors("dark_oak_mystic_trapdoor"),
                    mcwTrapdoors("dark_oak_paper_trapdoor"),
                    mcwTrapdoors("dark_oak_ranch_trapdoor"),
                    mcwTrapdoors("dark_oak_swamp_trapdoor"),
                    mcwTrapdoors("dark_oak_tropical_trapdoor"),
                    mcwTrapdoors("dark_oak_whispering_trapdoor"),
                    mcwWindows("dark_oak_shutter"),
                    mcwWindows("dark_oak_louvered_shutter")),
            family("cnm/trapdoor/mangrove", TRAPDOOR, minecraft("mangrove_trapdoor"),
                    mcwTrapdoors("mangrove_bamboo_trapdoor"),
                    mcwTrapdoors("mangrove_bark_trapdoor"),
                    mcwTrapdoors("mangrove_barn_trapdoor"),
                    mcwTrapdoors("mangrove_barred_trapdoor"),
                    mcwTrapdoors("mangrove_barrel_trapdoor"),
                    mcwTrapdoors("mangrove_beach_trapdoor"),
                    mcwTrapdoors("mangrove_blossom_trapdoor"),
                    mcwTrapdoors("mangrove_classic_trapdoor"),
                    mcwTrapdoors("mangrove_cottage_trapdoor"),
                    mcwTrapdoors("mangrove_four_panel_trapdoor"),
                    mcwTrapdoors("mangrove_glass_trapdoor"),
                    mcwTrapdoors("mangrove_mystic_trapdoor"),
                    mcwTrapdoors("mangrove_paper_trapdoor"),
                    mcwTrapdoors("mangrove_ranch_trapdoor"),
                    mcwTrapdoors("mangrove_tropical_trapdoor"),
                    mcwTrapdoors("mangrove_whispering_trapdoor"),
                    mcwWindows("mangrove_shutter"),
                    mcwWindows("mangrove_louvered_shutter")),
            family("cnm/trapdoor/cherry", TRAPDOOR, minecraft("cherry_trapdoor"),
                    mcwTrapdoors("cherry_bamboo_trapdoor"),
                    mcwTrapdoors("cherry_bark_trapdoor"),
                    mcwTrapdoors("cherry_barn_trapdoor"),
                    mcwTrapdoors("cherry_barred_trapdoor"),
                    mcwTrapdoors("cherry_barrel_trapdoor"),
                    mcwTrapdoors("cherry_beach_trapdoor"),
                    mcwTrapdoors("cherry_classic_trapdoor"),
                    mcwTrapdoors("cherry_cottage_trapdoor"),
                    mcwTrapdoors("cherry_four_panel_trapdoor"),
                    mcwTrapdoors("cherry_glass_trapdoor"),
                    mcwTrapdoors("cherry_mystic_trapdoor"),
                    mcwTrapdoors("cherry_paper_trapdoor"),
                    mcwTrapdoors("cherry_ranch_trapdoor"),
                    mcwTrapdoors("cherry_swamp_trapdoor"),
                    mcwTrapdoors("cherry_tropical_trapdoor"),
                    mcwTrapdoors("cherry_whispering_trapdoor"),
                    mcwWindows("cherry_shutter"),
                    mcwWindows("cherry_louvered_shutter")),
            family("cnm/trapdoor/pale_oak", TRAPDOOR, minecraft("pale_oak_trapdoor"),
                    mcwTrapdoors("pale_oak_bamboo_trapdoor"),
                    mcwTrapdoors("pale_oak_bark_trapdoor"),
                    mcwTrapdoors("pale_oak_barn_trapdoor"),
                    mcwTrapdoors("pale_oak_barred_trapdoor"),
                    mcwTrapdoors("pale_oak_barrel_trapdoor"),
                    mcwTrapdoors("pale_oak_beach_trapdoor"),
                    mcwTrapdoors("pale_oak_blossom_trapdoor"),
                    mcwTrapdoors("pale_oak_classic_trapdoor"),
                    mcwTrapdoors("pale_oak_cottage_trapdoor"),
                    mcwTrapdoors("pale_oak_four_panel_trapdoor"),
                    mcwTrapdoors("pale_oak_glass_trapdoor"),
                    mcwTrapdoors("pale_oak_mystic_trapdoor"),
                    mcwTrapdoors("pale_oak_paper_trapdoor"),
                    mcwTrapdoors("pale_oak_ranch_trapdoor"),
                    mcwTrapdoors("pale_oak_swamp_trapdoor"),
                    mcwTrapdoors("pale_oak_tropical_trapdoor"),
                    mcwWindows("pale_oak_shutter"),
                    mcwWindows("pale_oak_louvered_shutter")),
            family("cnm/trapdoor/crimson", TRAPDOOR, minecraft("crimson_trapdoor"),
                    mcwTrapdoors("crimson_bamboo_trapdoor"),
                    mcwTrapdoors("crimson_bark_trapdoor"),
                    mcwTrapdoors("crimson_barn_trapdoor"),
                    mcwTrapdoors("crimson_barrel_trapdoor"),
                    mcwTrapdoors("crimson_beach_trapdoor"),
                    mcwTrapdoors("crimson_blossom_trapdoor"),
                    mcwTrapdoors("crimson_classic_trapdoor"),
                    mcwTrapdoors("crimson_cottage_trapdoor"),
                    mcwTrapdoors("crimson_four_panel_trapdoor"),
                    mcwTrapdoors("crimson_glass_trapdoor"),
                    mcwTrapdoors("crimson_mystic_trapdoor"),
                    mcwTrapdoors("crimson_paper_trapdoor"),
                    mcwTrapdoors("crimson_ranch_trapdoor"),
                    mcwTrapdoors("crimson_swamp_trapdoor"),
                    mcwTrapdoors("crimson_tropical_trapdoor"),
                    mcwTrapdoors("crimson_whispering_trapdoor"),
                    mcwWindows("crimson_shutter"),
                    mcwWindows("crimson_louvered_shutter")),
            family("cnm/trapdoor/warped", TRAPDOOR, minecraft("warped_trapdoor"),
                    mcwTrapdoors("warped_bamboo_trapdoor"),
                    mcwTrapdoors("warped_bark_trapdoor"),
                    mcwTrapdoors("warped_barn_trapdoor"),
                    mcwTrapdoors("warped_barred_trapdoor"),
                    mcwTrapdoors("warped_barrel_trapdoor"),
                    mcwTrapdoors("warped_beach_trapdoor"),
                    mcwTrapdoors("warped_blossom_trapdoor"),
                    mcwTrapdoors("warped_classic_trapdoor"),
                    mcwTrapdoors("warped_cottage_trapdoor"),
                    mcwTrapdoors("warped_four_panel_trapdoor"),
                    mcwTrapdoors("warped_glass_trapdoor"),
                    mcwTrapdoors("warped_paper_trapdoor"),
                    mcwTrapdoors("warped_ranch_trapdoor"),
                    mcwTrapdoors("warped_swamp_trapdoor"),
                    mcwTrapdoors("warped_tropical_trapdoor"),
                    mcwTrapdoors("warped_whispering_trapdoor"),
                    mcwWindows("warped_shutter"),
                    mcwWindows("warped_louvered_shutter")),
            family("cnm/trapdoor/bamboo", TRAPDOOR, minecraft("bamboo_trapdoor"),
                    mcwTrapdoors("bamboo_trapdoor"),
                    mcwTrapdoors("bamboo_bark_trapdoor"),
                    mcwTrapdoors("bamboo_barn_trapdoor"),
                    mcwTrapdoors("bamboo_barred_trapdoor"),
                    mcwTrapdoors("bamboo_barrel_trapdoor"),
                    mcwTrapdoors("bamboo_beach_trapdoor"),
                    mcwTrapdoors("bamboo_blossom_trapdoor"),
                    mcwTrapdoors("bamboo_classic_trapdoor"),
                    mcwTrapdoors("bamboo_cottage_trapdoor"),
                    mcwTrapdoors("bamboo_four_panel_trapdoor"),
                    mcwTrapdoors("bamboo_glass_trapdoor"),
                    mcwTrapdoors("bamboo_mystic_trapdoor"),
                    mcwTrapdoors("bamboo_paper_trapdoor"),
                    mcwTrapdoors("bamboo_swamp_trapdoor"),
                    mcwTrapdoors("bamboo_tropical_trapdoor"),
                    mcwTrapdoors("bamboo_whispering_trapdoor"),
                    mcwWindows("bamboo_shutter")),
            family("cnm/trapdoor/iron", TRAPDOOR, minecraft("iron_trapdoor"),
                    mcwTrapdoors("metal_full_trapdoor"),
                    mcwTrapdoors("metal_trapdoor"),
                    mcwTrapdoors("metal_warning_trapdoor"),
                    mcwWindows("iron_shutter"))
    );

    private static final List<AuditedShapeFamily> WINDOWS = List.of(
            family("cnm/window/acacia_log", WINDOW, mcwWindows("acacia_window"),
                    mcwWindows("acacia_window2"),
                    mcwWindows("acacia_four_window"),
                    mcwWindows("acacia_pane_window")),
            family("cnm/window/acacia_planks", WINDOW, mcwWindows("acacia_plank_window"),
                    mcwWindows("acacia_plank_window2"),
                    mcwWindows("acacia_plank_four_window"),
                    mcwWindows("acacia_plank_pane_window")),
            family("cnm/window/andesite", WINDOW, mcwWindows("andesite_window"),
                    mcwWindows("andesite_window2"),
                    mcwWindows("andesite_four_window"),
                    mcwWindows("andesite_pane_window")),
            family("cnm/window/birch_log", WINDOW, mcwWindows("birch_window"),
                    mcwWindows("birch_window2"),
                    mcwWindows("birch_four_window"),
                    mcwWindows("birch_pane_window")),
            family("cnm/window/birch_planks", WINDOW, mcwWindows("birch_plank_window"),
                    mcwWindows("birch_plank_window2"),
                    mcwWindows("birch_plank_four_window"),
                    mcwWindows("birch_plank_pane_window")),
            family("cnm/window/bricks", WINDOW, mcwWindows("bricks_window"),
                    mcwWindows("bricks_window2"),
                    mcwWindows("bricks_four_window"),
                    mcwWindows("bricks_pane_window")),
            family("cnm/window/cherry_log", WINDOW, mcwWindows("cherry_window"),
                    mcwWindows("cherry_window2"),
                    mcwWindows("cherry_four_window"),
                    mcwWindows("cherry_pane_window")),
            family("cnm/window/cherry_planks", WINDOW, mcwWindows("cherry_plank_window"),
                    mcwWindows("cherry_plank_window2"),
                    mcwWindows("cherry_plank_four_window"),
                    mcwWindows("cherry_plank_pane_window")),
            family("cnm/window/crimson_planks", WINDOW, mcwWindows("crimson_planks_window"),
                    mcwWindows("crimson_planks_window2"),
                    mcwWindows("crimson_planks_four_window"),
                    mcwWindows("crimson_plank_pane_window")),
            family("cnm/window/crimson_stem", WINDOW, mcwWindows("crimson_stem_window"),
                    mcwWindows("crimson_stem_window2"),
                    mcwWindows("crimson_stem_four_window"),
                    mcwWindows("crimson_pane_window")),
            family("cnm/window/dark_oak_log", WINDOW, mcwWindows("dark_oak_window"),
                    mcwWindows("dark_oak_window2"),
                    mcwWindows("dark_oak_four_window"),
                    mcwWindows("dark_oak_pane_window")),
            family("cnm/window/dark_oak_planks", WINDOW, mcwWindows("dark_oak_plank_window"),
                    mcwWindows("dark_oak_plank_window2"),
                    mcwWindows("dark_oak_plank_four_window"),
                    mcwWindows("dark_oak_plank_pane_window")),
            family("cnm/window/dark_prismarine", WINDOW, mcwWindows("dark_prismarine_window"),
                    mcwWindows("dark_prismarine_window2"),
                    mcwWindows("dark_prismarine_four_window"),
                    mcwWindows("dark_prismarine_pane_window"),
                    mcwWindows("dark_prismarine_brick_gothic")),
            family("cnm/window/deepslate", WINDOW, mcwWindows("deepslate_window"),
                    mcwWindows("deepslate_window2"),
                    mcwWindows("deepslate_four_window"),
                    mcwWindows("deepslate_pane_window")),
            family("cnm/window/diorite", WINDOW, mcwWindows("diorite_window"),
                    mcwWindows("diorite_window2"),
                    mcwWindows("diorite_four_window"),
                    mcwWindows("diorite_pane_window")),
            family("cnm/window/granite", WINDOW, mcwWindows("granite_window"),
                    mcwWindows("granite_window2"),
                    mcwWindows("granite_four_window"),
                    mcwWindows("granite_pane_window")),
            family("cnm/window/iron_block", WINDOW, mcwWindows("metal_window"),
                    mcwWindows("metal_window2"),
                    mcwWindows("metal_four_window"),
                    mcwWindows("metal_pane_window")),
            family("cnm/window/jungle_log", WINDOW, mcwWindows("jungle_window"),
                    mcwWindows("jungle_window2"),
                    mcwWindows("jungle_four_window"),
                    mcwWindows("jungle_pane_window")),
            family("cnm/window/jungle_planks", WINDOW, mcwWindows("jungle_plank_window"),
                    mcwWindows("jungle_plank_window2"),
                    mcwWindows("jungle_plank_four_window"),
                    mcwWindows("jungle_plank_pane_window")),
            family("cnm/window/mangrove_log", WINDOW, mcwWindows("mangrove_window"),
                    mcwWindows("mangrove_window2"),
                    mcwWindows("mangrove_four_window"),
                    mcwWindows("mangrove_pane_window")),
            family("cnm/window/mangrove_planks", WINDOW, mcwWindows("mangrove_plank_window"),
                    mcwWindows("mangrove_plank_window2"),
                    mcwWindows("mangrove_plank_four_window"),
                    mcwWindows("mangrove_plank_pane_window")),
            family("cnm/window/oak_log", WINDOW, mcwWindows("oak_window"),
                    mcwWindows("oak_window2"),
                    mcwWindows("oak_four_window"),
                    mcwWindows("oak_pane_window")),
            family("cnm/window/oak_planks", WINDOW, mcwWindows("oak_plank_window"),
                    mcwWindows("oak_plank_window2"),
                    mcwWindows("oak_plank_four_window"),
                    mcwWindows("oak_plank_pane_window")),
            family("cnm/window/pale_oak_log", WINDOW, mcwWindows("pale_oak_window"),
                    mcwWindows("pale_oak_window2"),
                    mcwWindows("pale_oak_four_window"),
                    mcwWindows("pale_oak_pane_window")),
            family("cnm/window/pale_oak_planks", WINDOW, mcwWindows("pale_oak_plank_window"),
                    mcwWindows("pale_oak_plank_window2"),
                    mcwWindows("pale_oak_plank_four_window"),
                    mcwWindows("pale_oak_plank_pane_window")),
            family("cnm/window/polished_blackstone", WINDOW, mcwWindows("blackstone_window"),
                    mcwWindows("blackstone_window2"),
                    mcwWindows("blackstone_four_window"),
                    mcwWindows("blackstone_pane_window")),
            family("cnm/window/prismarine_bricks", WINDOW, mcwWindows("prismarine_window"),
                    mcwWindows("prismarine_window2"),
                    mcwWindows("prismarine_four_window"),
                    mcwWindows("prismarine_pane_window"),
                    mcwWindows("prismarine_brick_gothic")),
            family("cnm/window/quartz_block", WINDOW, mcwWindows("quartz_window"),
                    mcwWindows("quartz_window2"),
                    mcwWindows("quartz_four_window"),
                    mcwWindows("quartz_pane_window")),
            family("cnm/window/red_sandstone", WINDOW, mcwWindows("red_sandstone_window"),
                    mcwWindows("red_sandstone_window2"),
                    mcwWindows("red_sandstone_four_window"),
                    mcwWindows("red_sandstone_pane_window")),
            family("cnm/window/sandstone", WINDOW, mcwWindows("sandstone_window"),
                    mcwWindows("sandstone_window2"),
                    mcwWindows("sandstone_four_window"),
                    mcwWindows("sandstone_pane_window")),
            family("cnm/window/spruce_log", WINDOW, mcwWindows("spruce_window"),
                    mcwWindows("spruce_window2"),
                    mcwWindows("spruce_four_window"),
                    mcwWindows("spruce_pane_window")),
            family("cnm/window/spruce_planks", WINDOW, mcwWindows("spruce_plank_window"),
                    mcwWindows("spruce_plank_window2"),
                    mcwWindows("spruce_plank_four_window"),
                    mcwWindows("spruce_plank_pane_window")),
            family("cnm/window/stone", WINDOW, mcwWindows("stone_window"),
                    mcwWindows("stone_window2"),
                    mcwWindows("stone_four_window"),
                    mcwWindows("stone_pane_window")),
            family("cnm/window/stripped_acacia_log", WINDOW, mcwWindows("stripped_acacia_log_window"),
                    mcwWindows("stripped_acacia_log_window2"),
                    mcwWindows("stripped_acacia_log_four_window"),
                    mcwWindows("stripped_acacia_pane_window")),
            family("cnm/window/stripped_birch_log", WINDOW, mcwWindows("stripped_birch_log_window"),
                    mcwWindows("stripped_birch_log_window2"),
                    mcwWindows("stripped_birch_log_four_window"),
                    mcwWindows("stripped_birch_pane_window")),
            family("cnm/window/stripped_cherry_log", WINDOW, mcwWindows("stripped_cherry_log_window"),
                    mcwWindows("stripped_cherry_log_window2"),
                    mcwWindows("stripped_cherry_log_four_window"),
                    mcwWindows("stripped_cherry_pane_window")),
            family("cnm/window/stripped_crimson_stem", WINDOW, mcwWindows("stripped_crimson_stem_window"),
                    mcwWindows("stripped_crimson_stem_window2"),
                    mcwWindows("stripped_crimson_stem_four_window"),
                    mcwWindows("stripped_crimson_pane_window")),
            family("cnm/window/stripped_dark_oak_log", WINDOW, mcwWindows("stripped_dark_oak_log_window"),
                    mcwWindows("stripped_dark_oak_log_window2"),
                    mcwWindows("stripped_dark_oak_log_four_window"),
                    mcwWindows("stripped_dark_oak_pane_window")),
            family("cnm/window/stripped_jungle_log", WINDOW, mcwWindows("stripped_jungle_log_window"),
                    mcwWindows("stripped_jungle_log_window2"),
                    mcwWindows("stripped_jungle_log_four_window"),
                    mcwWindows("stripped_jungle_pane_window")),
            family("cnm/window/stripped_mangrove_log", WINDOW, mcwWindows("stripped_mangrove_log_window"),
                    mcwWindows("stripped_mangrove_log_window2"),
                    mcwWindows("stripped_mangrove_log_four_window"),
                    mcwWindows("stripped_mangrove_pane_window")),
            family("cnm/window/stripped_oak_log", WINDOW, mcwWindows("stripped_oak_log_window"),
                    mcwWindows("stripped_oak_log_window2"),
                    mcwWindows("stripped_oak_log_four_window"),
                    mcwWindows("stripped_oak_pane_window")),
            family("cnm/window/stripped_pale_oak_log", WINDOW, mcwWindows("stripped_pale_oak_log_window"),
                    mcwWindows("stripped_pale_oak_log_window2"),
                    mcwWindows("stripped_pale_oak_log_four_window"),
                    mcwWindows("stripped_pale_oak_pane_window")),
            family("cnm/window/stripped_spruce_log", WINDOW, mcwWindows("stripped_spruce_log_window"),
                    mcwWindows("stripped_spruce_log_window2"),
                    mcwWindows("stripped_spruce_log_four_window"),
                    mcwWindows("stripped_spruce_pane_window")),
            family("cnm/window/stripped_warped_stem", WINDOW, mcwWindows("stripped_warped_stem_window"),
                    mcwWindows("stripped_warped_stem_window2"),
                    mcwWindows("stripped_warped_stem_four_window"),
                    mcwWindows("stripped_warped_pane_window")),
            family("cnm/window/warped_planks", WINDOW, mcwWindows("warped_planks_window"),
                    mcwWindows("warped_planks_window2"),
                    mcwWindows("warped_planks_four_window"),
                    mcwWindows("warped_plank_pane_window")),
            family("cnm/window/warped_stem", WINDOW, mcwWindows("warped_stem_window"),
                    mcwWindows("warped_stem_window2"),
                    mcwWindows("warped_stem_four_window"),
                    mcwWindows("warped_pane_window"))
    );

    private static final List<AuditedShapeFamily> DISPLAY_FIXTURES = List.of(
            family("cnm/display_fixture/oak", DISPLAY_FIXTURE, minecraft("oak_sign"),
                    minecraft("oak_hanging_sign"), minecraft("oak_shelf")),
            family("cnm/display_fixture/spruce", DISPLAY_FIXTURE, minecraft("spruce_sign"),
                    minecraft("spruce_hanging_sign"), minecraft("spruce_shelf")),
            family("cnm/display_fixture/birch", DISPLAY_FIXTURE, minecraft("birch_sign"),
                    minecraft("birch_hanging_sign"), minecraft("birch_shelf")),
            family("cnm/display_fixture/jungle", DISPLAY_FIXTURE, minecraft("jungle_sign"),
                    minecraft("jungle_hanging_sign"), minecraft("jungle_shelf")),
            family("cnm/display_fixture/acacia", DISPLAY_FIXTURE, minecraft("acacia_sign"),
                    minecraft("acacia_hanging_sign"), minecraft("acacia_shelf")),
            family("cnm/display_fixture/dark_oak", DISPLAY_FIXTURE, minecraft("dark_oak_sign"),
                    minecraft("dark_oak_hanging_sign"), minecraft("dark_oak_shelf")),
            family("cnm/display_fixture/mangrove", DISPLAY_FIXTURE, minecraft("mangrove_sign"),
                    minecraft("mangrove_hanging_sign"), minecraft("mangrove_shelf")),
            family("cnm/display_fixture/cherry", DISPLAY_FIXTURE, minecraft("cherry_sign"),
                    minecraft("cherry_hanging_sign"), minecraft("cherry_shelf")),
            family("cnm/display_fixture/pale_oak", DISPLAY_FIXTURE, minecraft("pale_oak_sign"),
                    minecraft("pale_oak_hanging_sign"), minecraft("pale_oak_shelf")),
            family("cnm/display_fixture/bamboo", DISPLAY_FIXTURE, minecraft("bamboo_sign"),
                    minecraft("bamboo_hanging_sign"), minecraft("bamboo_shelf")),
            family("cnm/display_fixture/crimson", DISPLAY_FIXTURE, minecraft("crimson_sign"),
                    minecraft("crimson_hanging_sign"), minecraft("crimson_shelf")),
            family("cnm/display_fixture/warped", DISPLAY_FIXTURE, minecraft("warped_sign"),
                    minecraft("warped_hanging_sign"), minecraft("warped_shelf")),
            family("cnm/display_fixture/enderscape_veiled", DISPLAY_FIXTURE, enderscape("veiled_sign"),
                    enderscape("veiled_hanging_sign"), enderscape("veiled_shelf")),
            family("cnm/display_fixture/enderscape_celestial", DISPLAY_FIXTURE, enderscape("celestial_sign"),
                    enderscape("celestial_hanging_sign"), enderscape("celestial_shelf")),
            family("cnm/display_fixture/enderscape_murublight", DISPLAY_FIXTURE, enderscape("murublight_sign"),
                    enderscape("murublight_hanging_sign"), enderscape("murublight_shelf"))
    );

    private static final List<AuditedShapeFamily> FENCE_GATES = List.of(
            family("cnm/fence_gate/oak", FENCE_GATE, minecraft("oak_fence"),
                    minecraft("oak_fence_gate"), bbb("oak_frame"), bbb("oak_lattice")),
            family("cnm/fence_gate/spruce", FENCE_GATE, minecraft("spruce_fence"),
                    minecraft("spruce_fence_gate"), bbb("spruce_frame"), bbb("spruce_lattice")),
            family("cnm/fence_gate/birch", FENCE_GATE, minecraft("birch_fence"),
                    minecraft("birch_fence_gate"), bbb("birch_frame"), bbb("birch_lattice")),
            family("cnm/fence_gate/jungle", FENCE_GATE, minecraft("jungle_fence"),
                    minecraft("jungle_fence_gate"), bbb("jungle_frame"), bbb("jungle_lattice")),
            family("cnm/fence_gate/acacia", FENCE_GATE, minecraft("acacia_fence"),
                    minecraft("acacia_fence_gate"), bbb("acacia_frame"), bbb("acacia_lattice")),
            family("cnm/fence_gate/dark_oak", FENCE_GATE, minecraft("dark_oak_fence"),
                    minecraft("dark_oak_fence_gate"), bbb("dark_oak_frame"), bbb("dark_oak_lattice")),
            family("cnm/fence_gate/mangrove", FENCE_GATE, minecraft("mangrove_fence"),
                    minecraft("mangrove_fence_gate"), bbb("mangrove_frame"), bbb("mangrove_lattice")),
            family("cnm/fence_gate/cherry", FENCE_GATE, minecraft("cherry_fence"),
                    minecraft("cherry_fence_gate"), bbb("cherry_frame"), bbb("cherry_lattice")),
            family("cnm/fence_gate/pale_oak", FENCE_GATE, minecraft("pale_oak_fence"),
                    minecraft("pale_oak_fence_gate"), bbb("pale_oak_frame"), bbb("pale_oak_lattice")),
            family("cnm/fence_gate/bamboo", FENCE_GATE, minecraft("bamboo_fence"),
                    minecraft("bamboo_fence_gate"), bbb("bamboo_frame"), bbb("bamboo_lattice")),
            family("cnm/fence_gate/crimson", FENCE_GATE, minecraft("crimson_fence"),
                    minecraft("crimson_fence_gate"), bbb("crimson_frame"), bbb("crimson_lattice")),
            family("cnm/fence_gate/warped", FENCE_GATE, minecraft("warped_fence"),
                    minecraft("warped_fence_gate"), bbb("warped_frame"), bbb("warped_lattice")),
            family("cnm/fence_gate/ribbits_mossy_oak_planks", FENCE_GATE,
                    ribbits("mossy_oak_planks_fence"),
                    ribbits("mossy_oak_planks_fence_gate")),
            family("cnm/fence_gate/enderscape_veiled", FENCE_GATE, enderscape("veiled_fence"),
                    enderscape("veiled_fence_gate"), bbb("veiled_frame"), bbb("veiled_lattice")),
            family("cnm/fence_gate/enderscape_celestial", FENCE_GATE, enderscape("celestial_fence"),
                    enderscape("celestial_fence_gate"), bbb("celestial_frame"), bbb("celestial_lattice")),
            family("cnm/fence_gate/enderscape_murublight", FENCE_GATE, enderscape("murublight_fence"),
                    enderscape("murublight_fence_gate"), bbb("murublight_frame"), bbb("murublight_lattice"))
    );

    private static final List<AuditedShapeFamily> BAR_CHAINS = List.of(
            family("cnm/bar_chain/iron", BAR_CHAIN, minecraft("iron_bars"),
                    bbb("iron_fence"), minecraft("iron_chain"), aurorasLanterns("chandelier/iron")),
            family("cnm/bar_chain/copper", BAR_CHAIN, minecraft("copper_bars"),
                    minecraft("copper_chain"), aurorasLanterns("chandelier/copper")),
            family("cnm/bar_chain/exposed_copper", BAR_CHAIN, minecraft("exposed_copper_bars"),
                    minecraft("exposed_copper_chain"), aurorasLanterns("chandelier/exposed_copper")),
            family("cnm/bar_chain/weathered_copper", BAR_CHAIN, minecraft("weathered_copper_bars"),
                    minecraft("weathered_copper_chain"), aurorasLanterns("chandelier/weathered_copper")),
            family("cnm/bar_chain/oxidized_copper", BAR_CHAIN, minecraft("oxidized_copper_bars"),
                    minecraft("oxidized_copper_chain"), aurorasLanterns("chandelier/oxidized_copper")),
            family("cnm/bar_chain/waxed_copper", BAR_CHAIN, minecraft("waxed_copper_bars"),
                    minecraft("waxed_copper_chain"), aurorasLanterns("chandelier/waxed_copper")),
            family("cnm/bar_chain/waxed_exposed_copper", BAR_CHAIN,
                    minecraft("waxed_exposed_copper_bars"),
                    minecraft("waxed_exposed_copper_chain"),
                    aurorasLanterns("chandelier/waxed_exposed_copper")),
            family("cnm/bar_chain/waxed_weathered_copper", BAR_CHAIN,
                    minecraft("waxed_weathered_copper_bars"),
                    minecraft("waxed_weathered_copper_chain"),
                    aurorasLanterns("chandelier/waxed_weathered_copper")),
            family("cnm/bar_chain/waxed_oxidized_copper", BAR_CHAIN,
                    minecraft("waxed_oxidized_copper_bars"),
                    minecraft("waxed_oxidized_copper_chain"),
                    aurorasLanterns("chandelier/waxed_oxidized_copper")),
            family("cnm/bar_chain/enderscape_shadoline", BAR_CHAIN, enderscape("shadoline_bars"),
                    enderscape("shadoline_chain"))
    );

    private static final List<AuditedShapeFamily> BBB_DETAILS = List.of(
            family("cnm/bbb_detail/wood/oak", BBB_DETAIL, bbb("oak_trim"), bbb("oak_balustrade"), bbb("oak_support"), bbb("oak_pallet")),
            family("cnm/bbb_detail/wood/spruce", BBB_DETAIL, bbb("spruce_trim"), bbb("spruce_balustrade"), bbb("spruce_support"), bbb("spruce_pallet")),
            family("cnm/bbb_detail/wood/birch", BBB_DETAIL, bbb("birch_trim"), bbb("birch_balustrade"), bbb("birch_support"), bbb("birch_pallet")),
            family("cnm/bbb_detail/wood/jungle", BBB_DETAIL, bbb("jungle_trim"), bbb("jungle_balustrade"), bbb("jungle_support"), bbb("jungle_pallet")),
            family("cnm/bbb_detail/wood/acacia", BBB_DETAIL, bbb("acacia_trim"), bbb("acacia_balustrade"), bbb("acacia_support"), bbb("acacia_pallet")),
            family("cnm/bbb_detail/wood/dark_oak", BBB_DETAIL, bbb("dark_oak_trim"), bbb("dark_oak_balustrade"), bbb("dark_oak_support"), bbb("dark_oak_pallet")),
            family("cnm/bbb_detail/wood/crimson", BBB_DETAIL, bbb("crimson_trim"), bbb("crimson_balustrade"), bbb("crimson_support"), bbb("crimson_pallet")),
            family("cnm/bbb_detail/wood/warped", BBB_DETAIL, bbb("warped_trim"), bbb("warped_balustrade"), bbb("warped_support"), bbb("warped_pallet")),
            family("cnm/bbb_detail/wood/mangrove", BBB_DETAIL, bbb("mangrove_trim"), bbb("mangrove_balustrade"), bbb("mangrove_support"), bbb("mangrove_pallet")),
            family("cnm/bbb_detail/wood/bamboo", BBB_DETAIL, bbb("bamboo_trim"), bbb("bamboo_balustrade"), bbb("bamboo_support"), bbb("bamboo_pallet")),
            family("cnm/bbb_detail/wood/cherry", BBB_DETAIL, bbb("cherry_trim"), bbb("cherry_balustrade"), bbb("cherry_support"), bbb("cherry_pallet")),
            family("cnm/bbb_detail/wood/pale_oak", BBB_DETAIL, bbb("pale_oak_trim"), bbb("pale_oak_balustrade"), bbb("pale_oak_support"), bbb("pale_oak_pallet")),
            family("cnm/bbb_detail/wood/enderscape_veiled", BBB_DETAIL, bbb("veiled_trim"), bbb("veiled_balustrade"), bbb("veiled_support"), bbb("veiled_pallet")),
            family("cnm/bbb_detail/wood/enderscape_celestial", BBB_DETAIL, bbb("celestial_trim"), bbb("celestial_balustrade"), bbb("celestial_support"), bbb("celestial_pallet")),
            family("cnm/bbb_detail/wood/enderscape_murublight", BBB_DETAIL, bbb("murublight_trim"), bbb("murublight_balustrade"), bbb("murublight_support"), bbb("murublight_pallet")),
            family("cnm/bbb_detail/stone/stone", BBB_DETAIL, bbb("stone_column"), bbb("stone_urn"), bbb("stone_moulding"), bbb("stone_fence"), bbb("stone_frame")),
            family("cnm/bbb_detail/stone/blackstone", BBB_DETAIL, bbb("blackstone_column"), bbb("blackstone_urn"), bbb("blackstone_moulding"), bbb("blackstone_fence"), bbb("blackstone_frame")),
            family("cnm/bbb_detail/stone/deepslate", BBB_DETAIL, bbb("deepslate_column"), bbb("deepslate_urn"), bbb("deepslate_moulding"), bbb("deepslate_fence"), bbb("deepslate_frame")),
            family("cnm/bbb_detail/stone/nether_brick", BBB_DETAIL, bbb("nether_brick_column"), bbb("nether_brick_urn"), bbb("nether_brick_moulding"), bbb("nether_brick_fence"), bbb("nether_brick_frame")),
            family("cnm/bbb_detail/stone/sandstone", BBB_DETAIL, bbb("sandstone_column"), bbb("sandstone_urn"), bbb("sandstone_moulding"), bbb("sandstone_fence"), bbb("sandstone_frame")),
            family("cnm/bbb_detail/stone/red_sandstone", BBB_DETAIL, bbb("red_sandstone_column"), bbb("red_sandstone_urn"), bbb("red_sandstone_moulding"), bbb("red_sandstone_fence"), bbb("red_sandstone_frame")),
            family("cnm/bbb_detail/stone/quartz", BBB_DETAIL, bbb("quartz_column"), bbb("quartz_urn"), bbb("quartz_moulding"), bbb("quartz_fence"), bbb("quartz_frame"))
    );


    private static final List<AuditedShapeFamily> MASONRY = MasonryC12Families.families();

    private static final List<AuditedShapeFamily> BUILDING_ACCESSORIES = List.of(
            family("cnm/building_accessory/oak", BUILDING_ACCESSORY, minecraft("oak_button"),
                    minecraft("oak_pressure_plate"),
                    mcwPaths("oak_planks_path"),
                    mcwWindows("oak_log_parapet"),
                    mcwWindows("oak_plank_parapet"),
                    mcwWindows("oak_blinds"),
                    mcwWindows("oak_curtain_rod")),
            family("cnm/building_accessory/spruce", BUILDING_ACCESSORY, minecraft("spruce_button"),
                    minecraft("spruce_pressure_plate"),
                    mcwPaths("spruce_planks_path"),
                    mcwWindows("spruce_log_parapet"),
                    mcwWindows("spruce_plank_parapet"),
                    mcwWindows("spruce_blinds"),
                    mcwWindows("spruce_curtain_rod")),
            family("cnm/building_accessory/birch", BUILDING_ACCESSORY, minecraft("birch_button"),
                    minecraft("birch_pressure_plate"),
                    mcwPaths("birch_planks_path"),
                    mcwWindows("birch_log_parapet"),
                    mcwWindows("birch_plank_parapet"),
                    mcwWindows("birch_blinds"),
                    mcwWindows("birch_curtain_rod")),
            family("cnm/building_accessory/jungle", BUILDING_ACCESSORY, minecraft("jungle_button"),
                    minecraft("jungle_pressure_plate"),
                    mcwPaths("jungle_planks_path"),
                    mcwWindows("jungle_log_parapet"),
                    mcwWindows("jungle_plank_parapet"),
                    mcwWindows("jungle_blinds"),
                    mcwWindows("jungle_curtain_rod")),
            family("cnm/building_accessory/acacia", BUILDING_ACCESSORY, minecraft("acacia_button"),
                    minecraft("acacia_pressure_plate"),
                    mcwPaths("acacia_planks_path"),
                    mcwWindows("acacia_log_parapet"),
                    mcwWindows("acacia_plank_parapet"),
                    mcwWindows("acacia_blinds"),
                    mcwWindows("acacia_curtain_rod")),
            family("cnm/building_accessory/dark_oak", BUILDING_ACCESSORY, minecraft("dark_oak_button"),
                    minecraft("dark_oak_pressure_plate"),
                    mcwPaths("dark_oak_planks_path"),
                    mcwWindows("dark_oak_log_parapet"),
                    mcwWindows("dark_oak_plank_parapet"),
                    mcwWindows("dark_oak_blinds"),
                    mcwWindows("dark_oak_curtain_rod")),
            family("cnm/building_accessory/mangrove", BUILDING_ACCESSORY, minecraft("mangrove_button"),
                    minecraft("mangrove_pressure_plate"),
                    mcwPaths("mangrove_planks_path"),
                    mcwWindows("mangrove_log_parapet"),
                    mcwWindows("mangrove_plank_parapet"),
                    mcwWindows("mangrove_blinds"),
                    mcwWindows("mangrove_curtain_rod")),
            family("cnm/building_accessory/cherry", BUILDING_ACCESSORY, minecraft("cherry_button"),
                    minecraft("cherry_pressure_plate"),
                    mcwPaths("cherry_planks_path"),
                    mcwWindows("cherry_log_parapet"),
                    mcwWindows("cherry_plank_parapet"),
                    mcwWindows("cherry_blinds"),
                    mcwWindows("cherry_curtain_rod")),
            family("cnm/building_accessory/pale_oak", BUILDING_ACCESSORY, minecraft("pale_oak_button"),
                    minecraft("pale_oak_pressure_plate"),
                    mcwPaths("pale_oak_planks_path"),
                    mcwWindows("pale_oak_log_parapet"),
                    mcwWindows("pale_oak_plank_parapet"),
                    mcwWindows("pale_oak_blinds"),
                    mcwWindows("pale_oak_curtain_rod")),
            family("cnm/building_accessory/bamboo", BUILDING_ACCESSORY, minecraft("bamboo_button"),
                    minecraft("bamboo_pressure_plate"),
                    mcwPaths("bamboo_planks_path")),
            family("cnm/building_accessory/crimson", BUILDING_ACCESSORY, minecraft("crimson_button"),
                    minecraft("crimson_pressure_plate"),
                    mcwPaths("crimson_planks_path"),
                    mcwWindows("crimson_stem_parapet"),
                    mcwWindows("crimson_plank_parapet"),
                    mcwWindows("crimson_blinds"),
                    mcwWindows("crimson_curtain_rod")),
            family("cnm/building_accessory/warped", BUILDING_ACCESSORY, minecraft("warped_button"),
                    minecraft("warped_pressure_plate"),
                    mcwPaths("warped_planks_path"),
                    mcwWindows("warped_stem_parapet"),
                    mcwWindows("warped_plank_parapet"),
                    mcwWindows("warped_blinds"),
                    mcwWindows("warped_curtain_rod")),
            family("cnm/building_accessory/stone", BUILDING_ACCESSORY, minecraft("stone_button"),
                    minecraft("stone_pressure_plate"),
                    mcwPaths("stone_running_bond_path"),
                    mcwPaths("stone_strewn_rocky_path"),
                    mcwPaths("stone_windmill_weave_path"),
                    mcwPaths("stone_flagstone_path"),
                    mcwPaths("stone_crystal_floor_path"),
                    mcwPaths("cobblestone_diamond_paving"),
                    mcwPaths("cobblestone_basket_weave_paving"),
                    mcwPaths("cobblestone_square_paving"),
                    mcwPaths("cobblestone_honeycomb_paving"),
                    mcwPaths("cobblestone_clover_paving"),
                    mcwPaths("cobblestone_dumble_paving")),
            family("cnm/building_accessory/polished_blackstone", BUILDING_ACCESSORY,
                    minecraft("polished_blackstone_button"),
                    minecraft("polished_blackstone_pressure_plate"),
                    mcwWindows("blackstone_parapet")),
            family("cnm/building_accessory/gold", BUILDING_ACCESSORY,
                    minecraft("light_weighted_pressure_plate"),
                    mcwWindows("golden_curtain_rod")),
            family("cnm/building_accessory/iron", BUILDING_ACCESSORY,
                    minecraft("heavy_weighted_pressure_plate"),
                    mcwWindows("metal_curtain_rod")),
            family("cnm/building_accessory/andesite", BUILDING_ACCESSORY,
                    mcwPaths("andesite_running_bond_path"),
                    mcwPaths("andesite_strewn_rocky_path"),
                    mcwPaths("andesite_windmill_weave_path"),
                    mcwPaths("andesite_flagstone_path"),
                    mcwPaths("andesite_crystal_floor_path"),
                    mcwWindows("andesite_parapet"),
                    mcwPaths("andesite_diamond_paving"),
                    mcwPaths("andesite_basket_weave_paving"),
                    mcwPaths("andesite_square_paving"),
                    mcwPaths("andesite_honeycomb_paving"),
                    mcwPaths("andesite_clover_paving"),
                    mcwPaths("andesite_dumble_paving")),
            family("cnm/building_accessory/diorite", BUILDING_ACCESSORY,
                    mcwPaths("diorite_running_bond_path"),
                    mcwPaths("diorite_strewn_rocky_path"),
                    mcwPaths("diorite_windmill_weave_path"),
                    mcwPaths("diorite_flagstone_path"),
                    mcwPaths("diorite_crystal_floor_path"),
                    mcwWindows("diorite_parapet"),
                    mcwPaths("diorite_diamond_paving"),
                    mcwPaths("diorite_basket_weave_paving"),
                    mcwPaths("diorite_square_paving"),
                    mcwPaths("diorite_honeycomb_paving"),
                    mcwPaths("diorite_clover_paving"),
                    mcwPaths("diorite_dumble_paving")),
            family("cnm/building_accessory/granite", BUILDING_ACCESSORY,
                    mcwPaths("granite_running_bond_path"),
                    mcwPaths("granite_strewn_rocky_path"),
                    mcwPaths("granite_windmill_weave_path"),
                    mcwPaths("granite_flagstone_path"),
                    mcwPaths("granite_crystal_floor_path"),
                    mcwWindows("granite_parapet"),
                    mcwPaths("granite_diamond_paving"),
                    mcwPaths("granite_basket_weave_paving"),
                    mcwPaths("granite_square_paving"),
                    mcwPaths("granite_honeycomb_paving"),
                    mcwPaths("granite_clover_paving"),
                    mcwPaths("granite_dumble_paving")),
            family("cnm/building_accessory/sandstone", BUILDING_ACCESSORY,
                    mcwPaths("sandstone_running_bond_path"),
                    mcwPaths("sandstone_strewn_rocky_path"),
                    mcwPaths("sandstone_windmill_weave_path"),
                    mcwPaths("sandstone_flagstone_path"),
                    mcwPaths("sandstone_crystal_floor_path"),
                    mcwPaths("sandstone_diamond_paving"),
                    mcwPaths("sandstone_basket_weave_paving"),
                    mcwPaths("sandstone_square_paving"),
                    mcwPaths("sandstone_honeycomb_paving"),
                    mcwPaths("sandstone_clover_paving"),
                    mcwPaths("sandstone_dumble_paving")),
            family("cnm/building_accessory/red_sandstone", BUILDING_ACCESSORY,
                    mcwPaths("red_sandstone_running_bond_path"),
                    mcwPaths("red_sandstone_strewn_rocky_path"),
                    mcwPaths("red_sandstone_windmill_weave_path"),
                    mcwPaths("red_sandstone_flagstone_path"),
                    mcwPaths("red_sandstone_crystal_floor_path"),
                    mcwPaths("red_sandstone_diamond_paving"),
                    mcwPaths("red_sandstone_basket_weave_paving"),
                    mcwPaths("red_sandstone_square_paving"),
                    mcwPaths("red_sandstone_honeycomb_paving"),
                    mcwPaths("red_sandstone_clover_paving"),
                    mcwPaths("red_sandstone_dumble_paving")),
            family("cnm/building_accessory/brick", BUILDING_ACCESSORY,
                    mcwPaths("brick_running_bond_path"),
                    mcwPaths("brick_strewn_rocky_path"),
                    mcwPaths("brick_windmill_weave_path"),
                    mcwPaths("brick_flagstone_path"),
                    mcwPaths("brick_crystal_floor_path"),
                    mcwPaths("brick_diamond_paving"),
                    mcwPaths("brick_basket_weave_paving"),
                    mcwPaths("brick_square_paving"),
                    mcwPaths("brick_honeycomb_paving"),
                    mcwPaths("brick_clover_paving"),
                    mcwPaths("brick_dumble_paving")),
            family("cnm/building_accessory/mossy_stone", BUILDING_ACCESSORY,
                    mcwPaths("mossy_stone_running_bond_path"),
                    mcwPaths("mossy_stone_strewn_rocky_path"),
                    mcwPaths("mossy_stone_windmill_weave_path"),
                    mcwPaths("mossy_stone_flagstone_path"),
                    mcwPaths("mossy_stone_crystal_floor_path"),
                    mcwPaths("mossy_cobblestone_diamond_paving"),
                    mcwPaths("mossy_cobblestone_basket_weave_paving"),
                    mcwPaths("mossy_cobblestone_square_paving"),
                    mcwPaths("mossy_cobblestone_honeycomb_paving"),
                    mcwPaths("mossy_cobblestone_clover_paving"),
                    mcwPaths("mossy_cobblestone_dumble_paving")),
            family("cnm/building_accessory/cobbled_deepslate", BUILDING_ACCESSORY,
                    mcwPaths("cobbled_deepslate_running_bond_path"),
                    mcwPaths("cobbled_deepslate_strewn_rocky_path"),
                    mcwPaths("cobbled_deepslate_windmill_weave_path"),
                    mcwPaths("cobbled_deepslate_flagstone_path"),
                    mcwPaths("cobbled_deepslate_crystal_floor_path"),
                    mcwPaths("cobbled_deepslate_diamond_paving"),
                    mcwPaths("cobbled_deepslate_basket_weave_paving"),
                    mcwPaths("cobbled_deepslate_square_paving"),
                    mcwPaths("cobbled_deepslate_honeycomb_paving"),
                    mcwPaths("cobbled_deepslate_clover_paving"),
                    mcwPaths("cobbled_deepslate_dumble_paving")),
            family("cnm/building_accessory/deepslate", BUILDING_ACCESSORY,
                    mcwPaths("deepslate_running_bond_path"),
                    mcwPaths("deepslate_strewn_rocky_path"),
                    mcwPaths("deepslate_windmill_weave_path"),
                    mcwPaths("deepslate_flagstone_path"),
                    mcwPaths("deepslate_crystal_floor_path"),
                    mcwPaths("deepslate_diamond_paving"),
                    mcwPaths("deepslate_basket_weave_paving"),
                    mcwPaths("deepslate_square_paving"),
                    mcwPaths("deepslate_honeycomb_paving"),
                    mcwPaths("deepslate_clover_paving"),
                    mcwPaths("deepslate_dumble_paving")),
            family("cnm/building_accessory/mud_brick", BUILDING_ACCESSORY,
                    mcwPaths("mud_brick_running_bond_path"),
                    mcwPaths("mud_brick_strewn_rocky_path"),
                    mcwPaths("mud_brick_windmill_weave_path"),
                    mcwPaths("mud_brick_flagstone_path"),
                    mcwPaths("mud_brick_crystal_floor_path"),
                    mcwPaths("mud_brick_diamond_paving"),
                    mcwPaths("mud_brick_basket_weave_paving"),
                    mcwPaths("mud_brick_square_paving"),
                    mcwPaths("mud_brick_honeycomb_paving"),
                    mcwPaths("mud_brick_clover_paving"),
                    mcwPaths("mud_brick_dumble_paving")),
            family("cnm/building_accessory/blackstone", BUILDING_ACCESSORY,
                    mcwPaths("blackstone_running_bond_path"),
                    mcwPaths("blackstone_strewn_rocky_path"),
                    mcwPaths("blackstone_windmill_weave_path"),
                    mcwPaths("blackstone_flagstone_path"),
                    mcwPaths("blackstone_crystal_floor_path"),
                    mcwPaths("blackstone_diamond_paving"),
                    mcwPaths("blackstone_basket_weave_paving"),
                    mcwPaths("blackstone_square_paving"),
                    mcwPaths("blackstone_honeycomb_paving"),
                    mcwPaths("blackstone_clover_paving"),
                    mcwPaths("blackstone_dumble_paving")),
            family("cnm/building_accessory/dark_prismarine", BUILDING_ACCESSORY,
                    mcwPaths("dark_prismarine_running_bond_path"),
                    mcwPaths("dark_prismarine_strewn_rocky_path"),
                    mcwPaths("dark_prismarine_windmill_weave_path"),
                    mcwPaths("dark_prismarine_flagstone_path"),
                    mcwPaths("dark_prismarine_crystal_floor_path"),
                    mcwWindows("dark_prismarine_parapet"),
                    mcwPaths("dark_prismarine_diamond_paving"),
                    mcwPaths("dark_prismarine_basket_weave_paving"),
                    mcwPaths("dark_prismarine_square_paving"),
                    mcwPaths("dark_prismarine_honeycomb_paving"),
                    mcwPaths("dark_prismarine_clover_paving"),
                    mcwPaths("dark_prismarine_dumble_paving")),
            family("cnm/building_accessory/enderscape_veiled", BUILDING_ACCESSORY,
                    enderscape("veiled_button"), enderscape("veiled_pressure_plate")),
            family("cnm/building_accessory/enderscape_celestial", BUILDING_ACCESSORY,
                    enderscape("celestial_button"), enderscape("celestial_pressure_plate")),
            family("cnm/building_accessory/enderscape_murublight", BUILDING_ACCESSORY,
                    enderscape("murublight_button"), enderscape("murublight_pressure_plate")),
            family("cnm/building_accessory/enderscape_polished_end_stone", BUILDING_ACCESSORY,
                    enderscape("polished_end_stone_button"), enderscape("polished_end_stone_pressure_plate")),
            family("cnm/building_accessory/enderscape_polished_mirestone", BUILDING_ACCESSORY,
                    enderscape("polished_mirestone_button"), enderscape("polished_mirestone_pressure_plate")),
            family("cnm/building_accessory/enderscape_polished_veradite", BUILDING_ACCESSORY,
                    enderscape("polished_veradite_button"), enderscape("polished_veradite_pressure_plate")),
            family("cnm/building_accessory/enderscape_polished_kurodite", BUILDING_ACCESSORY,
                    enderscape("polished_kurodite_button"), enderscape("polished_kurodite_pressure_plate"))
    );

    private static final List<AuditedShapeFamily> FAMILIES = allFamilies();
    private static final Set<Identifier> UNIQUE_MEMBERS = uniqueMembers();
    private static final int LARGEST_FAMILY_SIZE = FAMILIES.stream()
            .mapToInt(family -> family.members().size())
            .max()
            .orElse(0);

    static {
        validateCatalog();
    }

    private AuditedShapeFamilies() {
    }

    public static List<AuditedShapeFamily> families() {
        return FAMILIES;
    }

    public static List<AuditedShapeFamily> families(AuditedShapeFamily.Category category) {
        return switch (category) {
            case TWO_HIGH_DOOR -> TWO_HIGH_DOORS;
            case THREE_HIGH_DOOR -> THREE_HIGH_DOORS;
            case TRAPDOOR -> TRAPDOORS;
            case WINDOW -> withoutC12RehomedMasonry(WINDOWS);
            case DISPLAY_FIXTURE -> DISPLAY_FIXTURES;
            case FENCE_GATE -> FENCE_GATES;
            case BAR_CHAIN -> BAR_CHAINS;
            case BBB_DETAIL -> withoutC12RehomedMasonry(BBB_DETAILS);
            case MASONRY_DETAIL -> MASONRY;
            case BUILDING_ACCESSORY -> withoutC12RehomedMasonry(BUILDING_ACCESSORIES);
        };
    }

    public static int uniqueMemberCount() {
        return UNIQUE_MEMBERS.size();
    }

    public static int largestFamilySize() {
        return LARGEST_FAMILY_SIZE;
    }

    private static AuditedShapeFamily family(
            String keyPath,
            AuditedShapeFamily.Category category,
            Identifier canonicalParent,
            Identifier... alternatives
    ) {
        List<Identifier> members = new ArrayList<>(alternatives.length + 1);
        members.add(canonicalParent);
        members.addAll(List.of(alternatives));
        return new AuditedShapeFamily(
                Identifier.fromNamespaceAndPath(KEY_NAMESPACE, keyPath),
                category,
                canonicalParent,
                members);
    }

    private static Identifier minecraft(String path) {
        return Identifier.fromNamespaceAndPath("minecraft", path);
    }

    private static Identifier mcwDoors(String path) {
        return Identifier.fromNamespaceAndPath("mcwdoors", path);
    }

    private static Identifier dramaticDoors(String path) {
        return Identifier.fromNamespaceAndPath("dramaticdoors", path);
    }

    private static Identifier mcwTrapdoors(String path) {
        return Identifier.fromNamespaceAndPath("mcwtrpdoors", path);
    }

    private static Identifier mcwPaths(String path) {
        return Identifier.fromNamespaceAndPath("mcwpaths", path);
    }

    private static Identifier aurorasLanterns(String path) {
        return Identifier.fromNamespaceAndPath("auroraslanterns", path);
    }

    private static Identifier bbb(String path) {
        return Identifier.fromNamespaceAndPath("bbb", path);
    }

    private static Identifier amc(String path) {
        return Identifier.fromNamespaceAndPath("architectural_material_closure", path);
    }

    private static Identifier ribbits(String path) {
        return Identifier.fromNamespaceAndPath("ribbits", path);
    }

    private static Identifier enderscape(String path) {
        return Identifier.fromNamespaceAndPath("enderscape", path);
    }

    private static Identifier mcwWindows(String path) {
        return Identifier.fromNamespaceAndPath("mcwwindows", path);
    }

    private static List<AuditedShapeFamily> withoutC12RehomedMasonry(List<AuditedShapeFamily> families) {
        return families.stream().filter(family -> !C12_REHOMED_MASONRY_KEYS.contains(family.key().getPath())).toList();
    }

    private static List<AuditedShapeFamily> allFamilies() {
        List<AuditedShapeFamily> families = new ArrayList<>(EXPECTED_FAMILY_COUNT);
        families.addAll(TWO_HIGH_DOORS);
        families.addAll(THREE_HIGH_DOORS);
        families.addAll(TRAPDOORS);
        families.addAll(withoutC12RehomedMasonry(WINDOWS));
        families.addAll(DISPLAY_FIXTURES);
        families.addAll(FENCE_GATES);
        families.addAll(BAR_CHAINS);
        families.addAll(withoutC12RehomedMasonry(BBB_DETAILS));
        families.addAll(MASONRY);
        families.addAll(withoutC12RehomedMasonry(BUILDING_ACCESSORIES));
        return List.copyOf(families);
    }

    @SafeVarargs
    private static List<AuditedShapeFamily> combined(List<AuditedShapeFamily>... groups) {
        List<AuditedShapeFamily> result = new ArrayList<>();
        for (List<AuditedShapeFamily> group : groups) result.addAll(group);
        return List.copyOf(result);
    }

    private static Set<Identifier> uniqueMembers() {
        Set<Identifier> members = new HashSet<>();
        for (AuditedShapeFamily family : FAMILIES) {
            for (Identifier member : family.members()) {
                if (!members.add(member)) {
                    throw new IllegalStateException("Member occurs in more than one audited family: " + member);
                }
            }
        }
        return Set.copyOf(members);
    }

    private static void validateCatalog() {
        if (FAMILIES.size() != EXPECTED_FAMILY_COUNT) {
            throw new IllegalStateException("Expected " + EXPECTED_FAMILY_COUNT
                    + " audited families but found " + FAMILIES.size());
        }
        if (UNIQUE_MEMBERS.size() != EXPECTED_UNIQUE_MEMBER_COUNT) {
            throw new IllegalStateException("Expected " + EXPECTED_UNIQUE_MEMBER_COUNT
                    + " unique audited members but found " + UNIQUE_MEMBERS.size());
        }
        if (LARGEST_FAMILY_SIZE != EXPECTED_LARGEST_FAMILY_SIZE) {
            throw new IllegalStateException("Expected largest family size " + EXPECTED_LARGEST_FAMILY_SIZE
                    + " but found " + LARGEST_FAMILY_SIZE);
        }

        Set<Identifier> keys = new HashSet<>();
        for (AuditedShapeFamily family : FAMILIES) {
            if (!keys.add(family.key())) {
                throw new IllegalStateException("Duplicate audited family key: " + family.key());
            }
            String requiredPrefix = "cnm/" + family.category().keySegment() + "/";
            if (!family.key().getPath().startsWith(requiredPrefix)) {
                throw new IllegalStateException("Category/key mismatch for audited family: " + family.key());
            }
        }
    }
}
