param([string]$ProjectRoot = (Join-Path $PSScriptRoot '..'))

$ErrorActionPreference = 'Stop'
function Get-LongPathText([string]$Path) {
    $full = [System.IO.Path]::GetFullPath($Path)
    return [System.IO.File]::ReadAllText("\\?\$full")
}
$main = Join-Path $ProjectRoot 'src\main'
$providerRoot = [System.IO.Path]::GetFullPath((Join-Path $ProjectRoot '..\nibaru'))
$adapter = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\NibaruProviderAdapter.java')
$scan = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\ClutterNoMoreVariantScanMixin.java')
$shape = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\ShapeMapOrderMixin.java')
$assetMixin = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\AssetGeneratorMixin.java')
$axisState = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\MaterialAxisState.java')
$axisModel = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\AxisModelContract.java')
$axisWriter = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\client\AxisGeneratedResources.java')
$nativeAxisModel = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\api\material\NativeAxisModelContract.java')
$nativeAxisWriter = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\tools\NativeAxisResourceGenerator.java')
$providerBuild = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'build.gradle')
$integrationMixins = Get-Content -Raw -LiteralPath (Join-Path $main 'resources\cnm_terrain_slabs_compat.mixins.json')
$verticalAssetMixin = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\GlazedVerticalAssetMixin.java')
$stepAssetMixin = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\GlazedStepAssetMixin.java')
$generatedLanguage = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\CnmGeneratedLanguage.java')
$refreshMixin = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\ProviderAssetRefreshMixin.java')
$stepTemplateMixin = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\StructuredStepTemplateMixin.java')
$weatheringMixin = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\ProviderWeatheringCopperMixin.java')
$dripstoneMixin = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\mixin\ProviderPointedDripstoneMixin.java')
$soulVertical = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\SoulSandVerticalSlabBlock.java')
$soulStep = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\SoulSandStepBlock.java')
$client = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\CnmTerrainCompatClient.java')
$bindings = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\ExistingDerivedGeometryBindings.java')
$tests = Get-Content -Raw -LiteralPath (Join-Path $ProjectRoot 'src\gametest\java\dev\aero\cnmterraincompat\gametest\LeafSemanticsGameTests.java')
$layerTests = Get-Content -Raw -LiteralPath (Join-Path $ProjectRoot 'src\gametest\java\dev\aero\cnmterraincompat\BgeLayerIntegrationGameTests.java')
$layerBlock = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\BgeLayerBlock.java')
$layerData = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\LayerGeneratedData.java')
$layerProjection = Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\client\LayerModelProjection.java')
$profiles = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\api\material\NibaruMaterialProfiles.java')
$profile = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\api\material\NibaruMaterialProfile.java')
$caps = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\api\material\BehaviorCapability.java')
$modBlocks = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\block\ModBlocks.java')
$materialAxis = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\api\material\MaterialAxisSemantics.java')
$axisSlab = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\block\axis\AxisSlab.java')
$axisStairs = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\block\axis\AxisStairs.java')
$providerRegistry = Get-Content -Raw -LiteralPath (Join-Path $providerRoot 'common\src\main\java\games\twinhead\moreslabsstairsandwalls\registry\ModRegistry.java')
$metadata = Get-Content -Raw -LiteralPath (Join-Path $main 'resources\fabric.mod.json')
$speciesGates = 'oak_leaves|spruce_leaves|birch_leaves|jungle_leaves|acacia_leaves|dark_oak_leaves|mangrove_leaves|cherry_leaves|azalea_leaves'
$checks = [ordered]@{
    'provider derives catalog from ModBlocks values' = ($profiles -match 'ModBlocks\.values\(\)')
    'profile exposes exact family and native geometries' = ($profile -match 'ModBlocks family' -and $profile -match 'Optional<Block> nativeSlab' -and $profile -match 'Optional<Block> nativeStair' -and $profile -match 'Optional<Block> nativeWall')
    'profile separates effective sources from native ownership' = ($profile -match 'Optional<Block> effectiveSlabSource' -and $profile -match 'Optional<Block> effectiveStairSource' -and $profiles -match 'BlockFamilies\.getFamily')
    'profile exposes visual and texture contracts' = ($profile -match 'VisualProfile visualProfile' -and $profile -match 'TextureRoles textureRoles' -and $profile -match 'VisualSupport visualSupport')
    'tint is explicit and independent' = ($profile -match 'TintProfile tintProfile' -and $profiles -match 'family == ModBlocks\.GRASS_BLOCK' -and $profiles -match 'family == ModBlocks\.MYCELIUM')
    'typed capabilities include adapted and deferred behavior' = ($caps -match 'LEAF_LIFECYCLE' -and $caps -match 'SPREADABLE' -and $caps -match 'FALLING' -and $caps -match 'OXIDIZABLE' -and $caps -match 'CONCRETE_HARDENING')
    'adapter supports leaf spreadable Path stripping and copper capabilities' = ($adapter -match 'BehaviorCapability\.LEAF_LIFECYCLE, BehaviorCapability\.SPREADABLE,' -and $adapter -match 'BehaviorCapability\.FLATTENABLE_TO_PATH' -and $adapter -match 'BehaviorCapability\.PATH_CONVERSION' -and $adapter -match 'BehaviorCapability\.STRIPPABLE' -and $adapter -match 'BehaviorCapability\.OXIDIZABLE' -and $adapter -match 'CopperSemantics')
    'Nibaru admission requires behavior and visual support' = ($scan -match 'NibaruProviderAdapter\.admissionSize' -and $adapter -match 'ADAPTED_VISUALS' -and $adapter -match '\.supported\(\)')
    'adapter has no species-specific leaf gate' = ($adapter -notmatch $speciesGates -and $scan -notmatch $speciesGates)
    'adapter has no Oak Grass or Dirt predicate methods' = ($adapter -notmatch 'isOak|isGrassSlab|isGrassStairs|isDirtSlab|isDirtStairs' -and $scan -notmatch 'isOak|isGrassSlab|isGrassStairs|isDirtSlab|isDirtStairs')
    'factory selection is capability driven' = ($adapter -match 'contains\(BehaviorCapability\.LEAF_LIFECYCLE\)' -and $adapter -match 'contains\(BehaviorCapability\.SPREADABLE\)' -and $adapter -match 'contains\(BehaviorCapability\.PATH_CONVERSION\)')
    'unsupported matrix is structured' = ($adapter -match 'record UnsupportedEntry' -and $adapter -match 'missingCapabilities')
    'ShapeMap receives exact profile edges' = ($shape -match 'addExactShapeMapEdges' -and $adapter -match 'profile\.canonicalParent\(\)\.asItem\(\)')
    'ShapeMap order uses generic parent segments' = ($shape -match 'applyProviderParentSegmentOrder' -and $shape -notmatch 'Oak|oak|Grass|grass' -and $adapter -match 'component membership')
    'legacy grass ownership is isolated migration metadata' = ($bindings -match 'withDefaultNamespace\("grass_block"\)' -and $bindings -notmatch 'import .*Tint|import .*BehaviorCapability')
    'existing owners receive generic runtime capability binding' = ($adapter -match 'Map<Block, RuntimeBinding> RUNTIME_BINDINGS' -and $adapter -match 'useComposedCapabilities' -and $adapter -match 'FLATTENABLE_TO_PATH')
    'legacy block classes have no constructor-time Path target' = ((Get-Content -Raw -LiteralPath (Join-Path $main 'java\dev\aero\cnmterraincompat\GrassVerticalSlab.java')) -notmatch 'Supplier<Block>|pathTarget')
    'provider texture resolver replaces shallow scraping' = ($assetMixin -match 'TextureRoles' -and $assetMixin -match 'getTextures' -and $assetMixin -match 'checkTint')
    'persistent provider asset cache is refreshed generically' = ($refreshMixin -match 'PROVIDER_PATH = "more_slabs_stairs_and_walls/"' -and $refreshMixin -match 'Optional\.empty\(\)' -and $refreshMixin -notmatch 'quartz|podzol|mycelium|nylium')
    'structured Step template selection is sampling-policy based' = ($stepTemplateMixin -match 'SurfaceSamplingPolicy\.NATIVE_STAIR_SURFACE_BAND' -and $stepTemplateMixin -match 'SurfaceSamplingPolicy\.PATH_LOWERED_SURFACE' -and $stepTemplateMixin -notmatch 'grass|podzol|mycelium|nylium')
    'Nylium is top-side-bottom without grass overlay semantics' = ($profiles -match 'ModBlocks\.CRIMSON_NYLIUM \|\| family == ModBlocks\.WARPED_NYLIUM' -and $profiles -match 'bottom = "netherrack"')
    'client tint selection consumes TintProfile' = ($client -match 'configureTintRegistrar' -and $client -notmatch 'isMycelium|MYCELIUM')
    'architecture tests assert 311 profiles' = ($tests -match 'profiles\.size\(\) == 311')
    'architecture tests cover exact wart and dirt path parents' = ($tests -match 'ModBlocks\.DIRT_PATH' -and $tests -match 'ModBlocks\.WARPED_WART' -and $tests -match 'ModBlocks\.CRIMSON_WART')
    'architecture tests cover capability representatives' = ($tests -match 'ModBlocks\.SAND' -and $tests -match 'CONCRETE_HARDENING' -and $tests -match 'ModBlocks\.COPPER_BLOCK' -and $tests -match 'ModBlocks\.HONEY_BLOCK')
    'wart semantic audit is fixture covered' = ($tests -match 'tintAndWartSemanticsAreIndependent' -and $tests -match 'leaves\.size\(\) == 11')
    'Quartz Pillar uses canonical side texture' = ($modBlocks -match 'QUARTZ_PILLAR\(builder\(Blocks\.QUARTZ_PILLAR\)\.setTextures\("quartz_pillar_side"')
    'Smooth Quartz retains verified vanilla bottom texture' = ($modBlocks -match 'SMOOTH_QUARTZ\(builder\(Blocks\.SMOOTH_QUARTZ\).*setAllTexture\("quartz_block_bottom"\)')
    'grass double model uses reusable semantic template' = ((Get-LongPathText (Join-Path $main 'resources\assets\clutternomore\models\block\more_slabs_stairs_and_walls\grass_block_step_double.json')) -match 'templates/provider/grass_overlay_step_double')
    'exact Canary 46 Layer-contract dependency declared' = ($metadata -match '=4\.2\.0\+26\.2-port-canary46-bge-layer-contract')
    'CNM language scan excludes both generated pack identities' = ($assetMixin -match 'method = "translatedKeys"' -and $assetMixin -match 'CnmGeneratedLanguage\.isSelfGeneratedPack' -and $generatedLanguage -match 'MODID \+ "-runtime"' -and $generatedLanguage -match '"file/" \+ packName')
    'generated Nibaru English coverage is catalog-wide' = ($tests -match 'generatedProviderGeometriesHaveEffectiveEnglishNames' -and $tests -match 'names\.size\(\) == 621' -and $tests -match 'providerPaths == 554' -and $tests -match 'ordinaryAliases == 67' -and $tests -match 'Oak Log Step' -and $tests -match 'Vertical Oak Log Slab')
    'material axis applicability comes from canonical parent state' = ($axisState -match 'canonicalParent\(\)\.defaultBlockState\(\)\.hasProperty\(AXIS\)' -and $axisState -notmatch 'getPath|substring|replace\(' -and $adapter -match 'MaterialAxisState\.applies\(profile\)' -and $adapter -match 'AxisVerticalSlabBlock' -and $adapter -match 'AxisStepBlock')
    'axis resource extension is data-derived and uses Minecraft model transforms' = ($axisWriter -match 'ResourceManager manager' -and $axisWriter -match 'AxisModelContract\.uvPolicy' -and $axisModel -match 'Quadrant\.fromXYZAngles' -and $axisModel -match 'STANDARD_ROTATED' -and $axisModel -match 'HORIZONTAL_ROTATED' -and $axisModel -match 'DIRECT_UV_LOCKED' -and $axisModel -notmatch 'addProperty\("uvlock"' -and $verticalAssetMixin -match 'AxisGeneratedResources\.extendVertical\(manager, parent, shape\)' -and $stepAssetMixin -match 'AxisGeneratedResources\.extendStep\(manager, parent, shape\)')
    'material axis fixtures cover exact catalog state and generated models' = ($tests -match 'materialAxisProfileInventoryAndRuntimeBindings' -and $tests -match 'axisTargets == 168' -and $tests -match 'materialAxisCanonicalModelPoliciesAreDataDerived' -and $tests -match 'materialAxisModelSelectorsResolveAndNormalizeTextures' -and $tests -match 'materialAxisModelFacesAndInverseGeometryRemainCanonical')
    'native axis applicability is canonical-state derived without names or lists' = ($materialAxis -match 'canonicalParent\.defaultBlockState\(\)\.hasProperty\(AXIS\)' -and $materialAxis -notmatch 'getPath|substring|replace\(' -and $providerRegistry -match 'MaterialAxisSemantics\.applies\(block\)')
    'native slabs and stairs keep independent state and pillar rotation' = ($axisSlab -match 'builder\.add\(AXIS\)' -and $axisSlab -match 'placementAxis\(existing, this, context\.getClickedFace\(\)\)' -and $axisSlab -match 'RotatedPillarBlock\.rotatePillar\(super\.rotate' -and $axisStairs -match 'builder\.add\(AXIS\)' -and $axisStairs -match 'context\.getClickedFace\(\)\.getAxis\(\)' -and $axisStairs -match 'RotatedPillarBlock\.rotatePillar\(super\.rotate' -and $axisStairs -notmatch 'mirror\(')
    'provider owns exhaustive static native axis resources' = ($nativeAxisWriter -match 'EXPECTED_AXIS_FAMILIES = 56' -and $nativeAxisWriter -match 'for \(ModBlocks family : ModBlocks\.values\(\)\)' -and $nativeAxisWriter -match 'NativeAxisModelContract\.uvPolicy' -and $nativeAxisWriter -match 'families != EXPECTED_AXIS_FAMILIES' -and $providerBuild -match 'generateNativeAxisResources' -and $providerBuild -match 'dependsOn generateNativeAxisResources' -and $nativeAxisModel -match 'SlabType\.BOTTOM' -and $nativeAxisModel -match 'StairsShape\.INNER_LEFT' -and $nativeAxisModel -notmatch 'addProperty\("uvlock"' -and $integrationMixins -notmatch 'NativeAxisAssetGeneratorMixin')
    'sparse source fixture covers exact catalog and ordering' = ($tests -match 'SPARSE_RECONCILIATION\|profiles=35' -and $tests -match 'Blocks\.STONE_SLAB' -and $tests -match 'Blocks\.PALE_OAK_SLAB')
    'copper adapter has no family allowlist or registry-name inference' = ($adapter -notmatch 'ModBlocks\.(?:COPPER|CUT_COPPER|CHISELED_COPPER|COPPER_GRATE)' -and $adapter -notmatch 'getPath|substring|replace\(')
    'CNM weathering callback delegates typed provider transitions' = ($weatheringMixin -match 'WeatheringVerticalSlabBlock' -and $weatheringMixin -match 'WeatheringStepBlock' -and $weatheringMixin -match 'NibaruProviderAdapter\.nextOxidation' -and $weatheringMixin -match 'changeOverTime' -and $weatheringMixin -notmatch 'ModBlocks|getPath|substring|replace\(')
    'sparse Cut Copper fixtures execute oxidation and interactions' = ($tests -match 'sparseCutCopperExecutesProviderNaturalOxidation' -and $tests -match 'SPARSE_CUT_COPPER_LIFECYCLE\|profiles=8' -and $tests -match 'SPARSE_CUT_COPPER_INTERACTIONS\|wax=vertical\|unwax=step\|scrape=vertical')
    'ROOTS remains adapted with expanded support matrix' = ($adapter -match 'VisualProfile\.ROOTS' -and $tests -match 'ROOTS_VISUAL\|profiles=1\|newVisualTargets=3\|newFullyReadyTargets=3' -and $tests -match 'visualSupported == 933' -and $tests -match 'fullyReady == 933')
    'Pale counterpart coverage is exact and capability-driven' = ($tests -match 'PALE_COVERAGE\|profiles=7\|nativeBlocks=19\|companionTargets=21\|matrix=933' -and $tests -match 'PALE_SEMANTICS\|stripping=PASS\|leafLifecycle=PASS\|paleMoss=PASS' -and $adapter -notmatch 'PALE_OAK|PALE_MOSS')
    'Glazed orientation uses specialized state and canonical generator extension' = ($adapter -match 'BehaviorCapability\.GLAZED_ORIENTATION' -and $adapter -match 'VisualProfile\.GLAZED_ORIENTED' -and $tests -match 'glazedGeneratedJsonCoversEveryIndependentState')
    'Magma is capability-driven and Soul Sand remains separate' = ($adapter -match 'BehaviorCapability\.MAGMA_DAMAGE' -and $adapter -match 'MagmaVerticalSlabBlock' -and $adapter -match 'MagmaStepBlock' -and $adapter -notmatch 'ModBlocks\.MAGMA_BLOCK' -and $tests -match 'MAGMA_SEMANTICS\|profiles=1\|targets=3\|tagged=6')
    'Pointed Dripstone parity reuses exact companion binding' = ($dripstoneMixin -match 'NibaruProviderAdapter\.runtimeBinding' -and $dripstoneMixin -match 'canonicalParent\(\) != Blocks\.DRIPSTONE_BLOCK' -and $dripstoneMixin -notmatch 'Identifier|BuiltInRegistries|getPath|vertical_dripstone|dripstone_step' -and $tests -match 'POINTED_DRIPSTONE_PARITY\|native=3')
    'Soul Sand is capability-driven and delegates provider semantics' = ($adapter -match 'BehaviorCapability\.SOUL_SAND_INTERACTION' -and $adapter -match 'SoulSandVerticalSlabBlock' -and $adapter -match 'SoulSandStepBlock' -and $adapter -notmatch 'ModBlocks\.SOUL_SAND' -and $soulVertical -match 'SoulSandSemantics' -and $soulStep -match 'SoulSandSemantics' -and $tests -match 'SOUL_SAND_SEMANTICS\|profiles=1\|targets=3')
    'Layer is BGE-owned and provider-material-driven' = ($layerBlock -match 'class BgeLayerBlock' -and $layerBlock -match 'NibaruMaterialProfile materialProfile' -and $adapter -match 'Geometry\.LAYER' -and $adapter -match 'BgeLayerSpecializedBlocks\.create' -and $metadata -notmatch 'building.?but.?better|\bbbb\b')
    'Layer family population is catalog-wide and non-recursive' = ($layerTests -match 'profiles\.size\(\) == 311' -and $layerTests -match 'automaticPopulationIsExactNonrecursiveAndOrdered' -and $layerData -match 'NibaruMaterialProfiles\.all\(\)' -and $layerData -match 'block == profile\.canonicalParent\(\)')
    'Layer resources are ordinary JSON from typed visual contracts' = ($layerProjection -match 'TextureRoles roles' -and $layerProjection -match 'SurfaceSamplingPolicy\.PATH_LOWERED_SURFACE' -and $layerProjection -match 'overlayUv' -and $layerData -match 'minecraft:set_count' -and $layerData -match 'writeTags\("block"')
}
Get-ChildItem -LiteralPath (Join-Path $main 'resources') -Recurse -Filter '*.json' | ForEach-Object {
    $full = [System.IO.Path]::GetFullPath($_.FullName)
    [System.IO.File]::ReadAllText("\\?\$full") | ConvertFrom-Json | Out-Null
}
$checks.GetEnumerator() | ForEach-Object { '{0}: {1}' -f ($(if ($_.Value) { 'PASS' } else { 'FAIL' })), $_.Key }
$failed = @($checks.GetEnumerator() | Where-Object { -not $_.Value })
if ($failed.Count -gt 0) { throw "Profile architecture fixture failed: $($failed.Name -join ', ')" }
'PASS: every integration JSON resource parsed'
