org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.157.0+26.2
macaws_doors_curse_file=8286482
macaws_paths_project=VRLhWB91
macaws_paths_version=LLYA3vec
macaws_trapdoors_project=n2fvCDlM
macaws_trapdoors_version=guJEg4jK
macaws_windows_project=C7I0BCni
macaws_windows_version=sNXCQQn1
mod_version=0.1.0-canary4
maven_group=dev.resivore
archives_base_name=interchangeable-block-families
