# Project
version=6.1.1-compat.2
java_version=25

# Metadata
mod_name=YungsApi
mod_full_name=YUNG's API
mod_id=yungsapi
mod_author=YUNGNICKYOUNG
mod_description=API Library for YUNG's minecraft mods.
mod_credits=Thanks so much to all my patrons!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.yungsapi
mc_version=26.2
mc_version_range_fabric=>=26.2

# Fabric
fabric_version=0.157.0
fabric_loader_version=0.19.3
clothconfig_version_fabric=26.2.155
modmenu_version_fabric=18.0.0-beta.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
