org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.157.0+26.2
qsn_maven_version=0.4.0+mc26.1-26.3-snapshot-1
inventory_search_maven_project=wIOLlhbN
inventory_search_maven_version=LS2Uzs3g
mod_version=0.1.0-canary12
maven_group=dev.resivore
archives_base_name=quick-stack-nearby-compat
