# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=4.1.6+26.2-mynx-canary25
maven_group=com.yungnickyoung.minecraft.ribbits
mod_id=ribbits
archives_name=ribbits
enabled_platforms=fabric
# Minecraft properties
minecraft_version=26.2
# Dependencies
architectury_api_version=20.0.1
fabric_loader_version=0.19.3
fabric_api_version=0.157.0+26.2
neoforge_version=21.10.32-beta
geckolib_version=5.5.1
cloth_version=26.2.155
modmenu_version=20.0.1
