org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.157.0+26.2
mod_version=0.1.0-canary13
maven_group=dev.resivore
archives_base_name=container-slot-reservations
double_barrels_tested_jar=doublebarrels-fabric-26.2-1.0.1+26.2-canary2.jar
double_barrels_tested_sha256=b2119e05c508880c7977551091515f0076dd3cdc2733e51340ac813925b553c0
