package com.fizzware.dramaticdoors.compat.registries;

import com.fizzware.dramaticdoors.compat.DDCompatAdvancement;
import com.fizzware.dramaticdoors.compat.DDCompatRecipe;
import com.fizzware.dramaticdoors.registry.DDNames;
import com.fizzware.dramaticdoors.registry.DDRegistry;

import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.state.properties.BlockSetType;

public class BWGCompat
{
	public static void registerCompat() {
		registerBlocksItems();
		registerRecipes();
	}
	
	private static void registerBlocksItems() {
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_ASPEN, DDNames.SHORT_BWG_ASPEN, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "aspen_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_BAOBAB, DDNames.SHORT_BWG_BAOBAB, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "baobab_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_BLUE_ENCHANTED, DDNames.SHORT_BWG_BLUE_ENCHANTED, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_BULBIS, DDNames.SHORT_BWG_BULBIS, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "bulbis_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_CIKA, DDNames.SHORT_BWG_CIKA, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "cika_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_CYPRESS, DDNames.SHORT_BWG_CYPRESS, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "cypress_door")), BlockSetType.MANGROVE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_EBONY, DDNames.SHORT_BWG_EBONY, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "ebony_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_EMBUR, DDNames.SHORT_BWG_EMBUR, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "embur_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_ETHER, DDNames.SHORT_BWG_ETHER, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "ether_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_FIR, DDNames.SHORT_BWG_FIR, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "fir_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_FLORUS, DDNames.SHORT_BWG_FLORUS, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "florus_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_GREEN_ENCHANTED, DDNames.SHORT_BWG_GREEN_ENCHANTED, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_HOLLY, DDNames.SHORT_BWG_HOLLY, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "holly_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_IMPARIUS, DDNames.SHORT_BWG_IMPARIUS, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "imparius_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_IRONWOOD, DDNames.SHORT_BWG_IRONWOOD, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "ironwood_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_JACARANDA, DDNames.SHORT_BWG_JACARANDA, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "jacaranda_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_MAHOGANY, DDNames.SHORT_BWG_MAHOGANY, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "mahogany_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_MAPLE, DDNames.SHORT_BWG_MAPLE, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "maple_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_NIGHTSHADE, DDNames.SHORT_BWG_NIGHTSHADE, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "nightshade_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_PALM, DDNames.SHORT_BWG_PALM, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "palm_door")), BlockSetType.JUNGLE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_PINE, DDNames.SHORT_BWG_PINE, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "pine_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_RAINBOW_EUCALYPTUS, DDNames.SHORT_BWG_RAINBOW_EUCALYPTUS, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_REDWOOD, DDNames.SHORT_BWG_REDWOOD, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "redwood_door")), BlockSetType.SPRUCE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_SAKURA, DDNames.SHORT_BWG_SAKURA, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "sakura_door")), BlockSetType.CHERRY, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_SKYRIS, DDNames.SHORT_BWG_SKYRIS, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "skyris_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_SYTHIAN, DDNames.SHORT_BWG_SYTHIAN, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "sythian_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_WHITE_MANGROVE, DDNames.SHORT_BWG_WHITE_MANGROVE, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door")), BlockSetType.MANGROVE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_WILLOW, DDNames.SHORT_BWG_WILLOW, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "willow_door")), BlockSetType.MANGROVE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_WITCH_HAZEL, DDNames.SHORT_BWG_WITCH_HAZEL, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_BWG_ZELKOVA, DDNames.SHORT_BWG_ZELKOVA, DDRegistry.getBlockFromIdentifier(Identifier.fromNamespaceAndPath("biomeswevegone", "zelkova_door")), BlockSetType.OAK, true);
	}
	
	private static void registerRecipes() {
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_ASPEN, Identifier.fromNamespaceAndPath("biomeswevegone", "aspen_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_BAOBAB, Identifier.fromNamespaceAndPath("biomeswevegone", "baobab_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_BLUE_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_BULBIS, Identifier.fromNamespaceAndPath("biomeswevegone", "bulbis_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_CIKA, Identifier.fromNamespaceAndPath("biomeswevegone", "cika_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_CYPRESS, Identifier.fromNamespaceAndPath("biomeswevegone", "cypress_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_EBONY, Identifier.fromNamespaceAndPath("biomeswevegone", "ebony_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_EMBUR, Identifier.fromNamespaceAndPath("biomeswevegone", "embur_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_ETHER, Identifier.fromNamespaceAndPath("biomeswevegone", "ether_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_FIR, Identifier.fromNamespaceAndPath("biomeswevegone", "fir_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_FLORUS, Identifier.fromNamespaceAndPath("biomeswevegone", "florus_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_GREEN_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_HOLLY, Identifier.fromNamespaceAndPath("biomeswevegone", "holly_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_IMPARIUS, Identifier.fromNamespaceAndPath("biomeswevegone", "imparius_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_IRONWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "ironwood_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_JACARANDA, Identifier.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_MAHOGANY, Identifier.fromNamespaceAndPath("biomeswevegone", "mahogany_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_MAPLE, Identifier.fromNamespaceAndPath("biomeswevegone", "maple_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_NIGHTSHADE, Identifier.fromNamespaceAndPath("biomeswevegone", "nightshade_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_PALM, Identifier.fromNamespaceAndPath("biomeswevegone", "palm_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_PINE, Identifier.fromNamespaceAndPath("biomeswevegone", "pine_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_RAINBOW_EUCALYPTUS, Identifier.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_REDWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "redwood_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_SAKURA, Identifier.fromNamespaceAndPath("biomeswevegone", "sakura_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_SKYRIS, Identifier.fromNamespaceAndPath("biomeswevegone", "skyris_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_SYTHIAN, Identifier.fromNamespaceAndPath("biomeswevegone", "sythian_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_WHITE_MANGROVE, Identifier.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_WILLOW, Identifier.fromNamespaceAndPath("biomeswevegone", "willow_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_WITCH_HAZEL, Identifier.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_BWG_ZELKOVA, Identifier.fromNamespaceAndPath("biomeswevegone", "zelkova_door"), true);
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_ASPEN, Identifier.fromNamespaceAndPath("biomeswevegone", "aspen_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_BAOBAB, Identifier.fromNamespaceAndPath("biomeswevegone", "baobab_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_BLUE_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_BULBIS, Identifier.fromNamespaceAndPath("biomeswevegone", "bulbis_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_CIKA, Identifier.fromNamespaceAndPath("biomeswevegone", "cika_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_CYPRESS, Identifier.fromNamespaceAndPath("biomeswevegone", "cypress_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_EBONY, Identifier.fromNamespaceAndPath("biomeswevegone", "ebony_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_EMBUR, Identifier.fromNamespaceAndPath("biomeswevegone", "embur_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_ETHER, Identifier.fromNamespaceAndPath("biomeswevegone", "ether_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_FIR, Identifier.fromNamespaceAndPath("biomeswevegone", "fir_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_FLORUS, Identifier.fromNamespaceAndPath("biomeswevegone", "florus_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_GREEN_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_HOLLY, Identifier.fromNamespaceAndPath("biomeswevegone", "holly_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_IMPARIUS, Identifier.fromNamespaceAndPath("biomeswevegone", "imparius_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_IRONWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "ironwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_JACARANDA, Identifier.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_MAHOGANY, Identifier.fromNamespaceAndPath("biomeswevegone", "mahogany_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_MAPLE, Identifier.fromNamespaceAndPath("biomeswevegone", "maple_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_NIGHTSHADE, Identifier.fromNamespaceAndPath("biomeswevegone", "nightshade_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_PALM, Identifier.fromNamespaceAndPath("biomeswevegone", "palm_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_PINE, Identifier.fromNamespaceAndPath("biomeswevegone", "pine_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_RAINBOW_EUCALYPTUS, Identifier.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_REDWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "redwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_SAKURA, Identifier.fromNamespaceAndPath("biomeswevegone", "sakura_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_SKYRIS, Identifier.fromNamespaceAndPath("biomeswevegone", "skyris_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_SYTHIAN, Identifier.fromNamespaceAndPath("biomeswevegone", "sythian_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_WHITE_MANGROVE, Identifier.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_WILLOW, Identifier.fromNamespaceAndPath("biomeswevegone", "willow_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_WITCH_HAZEL, Identifier.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_BWG_ZELKOVA, Identifier.fromNamespaceAndPath("biomeswevegone", "zelkova_door"));
		
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_ASPEN, Identifier.fromNamespaceAndPath("biomeswevegone", "aspen_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_BAOBAB, Identifier.fromNamespaceAndPath("biomeswevegone", "baobab_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_BLUE_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_BULBIS, Identifier.fromNamespaceAndPath("biomeswevegone", "bulbis_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_CIKA, Identifier.fromNamespaceAndPath("biomeswevegone", "cika_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_CYPRESS, Identifier.fromNamespaceAndPath("biomeswevegone", "cypress_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_EBONY, Identifier.fromNamespaceAndPath("biomeswevegone", "ebony_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_EMBUR, Identifier.fromNamespaceAndPath("biomeswevegone", "embur_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_ETHER, Identifier.fromNamespaceAndPath("biomeswevegone", "ether_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_FIR, Identifier.fromNamespaceAndPath("biomeswevegone", "fir_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_FLORUS, Identifier.fromNamespaceAndPath("biomeswevegone", "florus_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_GREEN_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_HOLLY, Identifier.fromNamespaceAndPath("biomeswevegone", "holly_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_IMPARIUS, Identifier.fromNamespaceAndPath("biomeswevegone", "imparius_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_IRONWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "ironwood_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_JACARANDA, Identifier.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_MAHOGANY, Identifier.fromNamespaceAndPath("biomeswevegone", "mahogany_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_MAPLE, Identifier.fromNamespaceAndPath("biomeswevegone", "maple_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_NIGHTSHADE, Identifier.fromNamespaceAndPath("biomeswevegone", "nightshade_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_PALM, Identifier.fromNamespaceAndPath("biomeswevegone", "palm_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_PINE, Identifier.fromNamespaceAndPath("biomeswevegone", "pine_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_RAINBOW_EUCALYPTUS, Identifier.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_REDWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "redwood_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_SKYRIS, Identifier.fromNamespaceAndPath("biomeswevegone", "skyris_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_SAKURA, Identifier.fromNamespaceAndPath("biomeswevegone", "sakura_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_SYTHIAN, Identifier.fromNamespaceAndPath("biomeswevegone", "sythian_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_WHITE_MANGROVE, Identifier.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_WILLOW, Identifier.fromNamespaceAndPath("biomeswevegone", "willow_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_WITCH_HAZEL, Identifier.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_BWG_ZELKOVA, Identifier.fromNamespaceAndPath("biomeswevegone", "zelkova_door"), true);
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_ASPEN, Identifier.fromNamespaceAndPath("biomeswevegone", "aspen_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_BAOBAB, Identifier.fromNamespaceAndPath("biomeswevegone", "baobab_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_BLUE_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "blue_enchanted_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_BULBIS, Identifier.fromNamespaceAndPath("biomeswevegone", "bulbis_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_CIKA, Identifier.fromNamespaceAndPath("biomeswevegone", "cika_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_CYPRESS, Identifier.fromNamespaceAndPath("biomeswevegone", "cypress_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_EBONY, Identifier.fromNamespaceAndPath("biomeswevegone", "ebony_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_EMBUR, Identifier.fromNamespaceAndPath("biomeswevegone", "embur_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_ETHER, Identifier.fromNamespaceAndPath("biomeswevegone", "ether_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_FIR, Identifier.fromNamespaceAndPath("biomeswevegone", "fir_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_FLORUS, Identifier.fromNamespaceAndPath("biomeswevegone", "florus_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_GREEN_ENCHANTED, Identifier.fromNamespaceAndPath("biomeswevegone", "green_enchanted_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_HOLLY, Identifier.fromNamespaceAndPath("biomeswevegone", "holly_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_IMPARIUS, Identifier.fromNamespaceAndPath("biomeswevegone", "imparius_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_IRONWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "ironwood_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_JACARANDA, Identifier.fromNamespaceAndPath("biomeswevegone", "jacaranda_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_MAHOGANY, Identifier.fromNamespaceAndPath("biomeswevegone", "mahogany_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_MAPLE, Identifier.fromNamespaceAndPath("biomeswevegone", "maple_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_NIGHTSHADE, Identifier.fromNamespaceAndPath("biomeswevegone", "nightshade_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_PALM, Identifier.fromNamespaceAndPath("biomeswevegone", "palm_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_PINE, Identifier.fromNamespaceAndPath("biomeswevegone", "pine_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_RAINBOW_EUCALYPTUS, Identifier.fromNamespaceAndPath("biomeswevegone", "rainbow_eucalyptus_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_REDWOOD, Identifier.fromNamespaceAndPath("biomeswevegone", "redwood_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_SAKURA, Identifier.fromNamespaceAndPath("biomeswevegone", "sakura_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_SKYRIS, Identifier.fromNamespaceAndPath("biomeswevegone", "skyris_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_SYTHIAN, Identifier.fromNamespaceAndPath("biomeswevegone", "sythian_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_WHITE_MANGROVE, Identifier.fromNamespaceAndPath("biomeswevegone", "white_mangrove_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_WILLOW, Identifier.fromNamespaceAndPath("biomeswevegone", "willow_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_WITCH_HAZEL, Identifier.fromNamespaceAndPath("biomeswevegone", "witch_hazel_door"), "tall_bwg_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_BWG_ZELKOVA, Identifier.fromNamespaceAndPath("biomeswevegone", "zelkova_door"), "tall_bwg_wooden_door");
	}
}
